// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TShift.Infrastructure.Persistence;

#nullable disable

namespace TShift.Infrastructure.Migrations
{
    [DbContext(typeof(TShiftDbContext))]
    [Migration("20260910231509_DenetimKaydi")]
    partial class DenetimKaydi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TShift.Domain.Calisanlar.Calisan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ad");

                    b.Property<Guid?>("BirincilEkipId")
                        .HasColumnType("uuid")
                        .HasColumnName("birincil_team_id");

                    b.Property<Guid>("DepartmanId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("DisSistemId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dis_sistem_id");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint")
                        .HasColumnName("durum");

                    b.Property<string>("Eposta")
                        .HasColumnType("citext")
                        .HasColumnName("eposta");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("IseGiris")
                        .HasColumnType("date")
                        .HasColumnName("ise_giris");

                    b.Property<DateOnly?>("IstenCikis")
                        .HasColumnType("date")
                        .HasColumnName("isten_cikis");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PersonelNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("personel_no");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("soyad");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefon");

                    b.HasKey("Id");

                    b.HasIndex("BirincilEkipId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("KiraciId", "PersonelNo")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_tenant_personel_no");

                    b.HasIndex("KiraciId", "DepartmanId", "Durum")
                        .HasDatabaseName("ix_employees_tenant_dept_durum");

                    b.ToTable("employees", "public");
                });

            modelBuilder.Entity("TShift.Domain.Calisanlar.CalisanSozlesmesi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<DateOnly>("Baslangic")
                        .HasColumnType("date")
                        .HasColumnName("baslangic");

                    b.Property<DateOnly?>("Bitis")
                        .HasColumnType("date")
                        .HasColumnName("bitis");

                    b.Property<Guid>("CalisanId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("GunlukAzamiSaat")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("gunluk_azami_saat");

                    b.Property<decimal>("HaftalikSaat")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("haftalik_saat");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Tip")
                        .HasColumnType("smallint")
                        .HasColumnName("tip");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId", "Aktif")
                        .HasDatabaseName("ix_contracts_employee_aktif");

                    b.ToTable("employee_contracts", "public");
                });

            modelBuilder.Entity("TShift.Domain.Denetim.DenetimKaydi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ip")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("ip");

                    b.Property<short>("Islem")
                        .HasColumnType("smallint")
                        .HasColumnName("islem");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Oncesi")
                        .HasColumnType("jsonb")
                        .HasColumnName("oncesi");

                    b.Property<string>("Sonrasi")
                        .HasColumnType("jsonb")
                        .HasColumnName("sonrasi");

                    b.Property<string>("Tarayici")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("user_agent");

                    b.Property<string>("Varlik")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("varlik");

                    b.Property<Guid>("VarlikId")
                        .HasColumnType("uuid")
                        .HasColumnName("varlik_id");

                    b.Property<DateTimeOffset>("Zaman")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("zaman");

                    b.HasKey("Id");

                    b.HasIndex("KiraciId");

                    b.HasIndex("Zaman")
                        .HasDatabaseName("ix_audit_zaman");

                    b.HasIndex("KullaniciId", "Zaman")
                        .HasDatabaseName("ix_audit_kullanici");

                    b.HasIndex("Varlik", "VarlikId", "Zaman")
                        .HasDatabaseName("ix_audit_varlik");

                    b.ToTable("audit_log", "public");
                });

            modelBuilder.Entity("TShift.Domain.Kimlik.GirisDenemesi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Basarili")
                        .HasColumnType("boolean")
                        .HasColumnName("basarili");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("eposta");

                    b.Property<string>("FirmaSlug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("firma_slug");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ip")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Tarayici")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("user_agent");

                    b.Property<DateTimeOffset>("Zaman")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("zaman");

                    b.HasKey("Id");

                    b.HasIndex("Eposta", "Zaman")
                        .HasDatabaseName("ix_login_attempts_eposta");

                    b.HasIndex("Ip", "Zaman")
                        .HasDatabaseName("ix_login_attempts_ip");

                    b.ToTable("login_attempts", "public");
                });

            modelBuilder.Entity("TShift.Domain.Kimlik.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ad");

                    b.Property<short>("BasarisizGiris")
                        .HasColumnType("smallint")
                        .HasColumnName("basarisiz_giris");

                    b.Property<Guid?>("CalisanId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("DisKimlikId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dis_kimlik_id");

                    b.Property<string>("DisKimlikSaglayici")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("dis_kimlik_saglayici");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint")
                        .HasColumnName("durum");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("eposta");

                    b.Property<bool>("EpostaDogrulandi")
                        .HasColumnType("boolean")
                        .HasColumnName("eposta_dogrulandi");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("KilitBitis")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kilit_bitis");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("MfaAktif")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_aktif");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("SonGiris")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("son_giris");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("soyad");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefon");

                    b.HasKey("Id");

                    b.HasIndex("KiraciId", "Eposta")
                        .IsUnique()
                        .HasDatabaseName("ux_users_tenant_eposta");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("TShift.Domain.Kimlik.KullaniciKimlikBilgisi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Algoritma")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("algoritma");

                    b.Property<DateTimeOffset>("DegisimZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("degisim_zamani");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("sifre_hash");

                    b.Property<bool>("ZorunluDegisim")
                        .HasColumnType("boolean")
                        .HasColumnName("zorunlu_degisim");

                    b.HasKey("Id");

                    b.HasIndex("KiraciId");

                    b.HasIndex("KullaniciId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_credentials_user");

                    b.ToTable("user_credentials", "public");
                });

            modelBuilder.Entity("TShift.Domain.Kimlik.YenilemeJetonu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Bitis")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bitis");

                    b.Property<string>("Cihaz")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cihaz");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ip")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("ip");

                    b.Property<short?>("IptalSebebi")
                        .HasColumnType("smallint")
                        .HasColumnName("iptal_sebebi");

                    b.Property<DateTimeOffset?>("IptalZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iptal_zamani");

                    b.Property<string>("JetonOzeti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OncekiJetonOzeti")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("onceki_token_hash");

                    b.Property<DateTimeOffset>("SonKullanim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("son_kullanim");

                    b.HasKey("Id");

                    b.HasIndex("JetonOzeti")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("KiraciId");

                    b.HasIndex("KullaniciId", "IptalZamani")
                        .HasDatabaseName("ix_refresh_tokens_user");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("TShift.Domain.Kiracilar.Kiraci", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad");

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("birim_adi");

                    b.Property<DateOnly?>("DenemeBitis")
                        .HasColumnType("date")
                        .HasColumnName("deneme_bitis");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint")
                        .HasColumnName("durum");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<short>("HaftaBaslangic")
                        .HasColumnType("smallint")
                        .HasColumnName("hafta_baslangic");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SektorPaketi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sektor_paketi");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("ZamanDilimi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("zaman_dilimi");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_slug");

                    b.ToTable("tenants", "public");
                });

            modelBuilder.Entity("TShift.Domain.Organizasyon.Departman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AcilisSaat")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("acilis_saat");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<short>("CalismaTipi")
                        .HasColumnType("smallint")
                        .HasColumnName("calisma_tipi");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("KapanisSaat")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("kapanis_saat");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kod");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("UstDepartmanId")
                        .HasColumnType("uuid")
                        .HasColumnName("ust_department_id");

                    b.HasKey("Id");

                    b.HasIndex("KiraciId", "Kod")
                        .IsUnique()
                        .HasDatabaseName("ux_departments_tenant_kod");

                    b.ToTable("departments", "public");
                });

            modelBuilder.Entity("TShift.Domain.Organizasyon.Ekip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<Guid>("DepartmanId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kod");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("KiraciId", "Kod")
                        .IsUnique()
                        .HasDatabaseName("ux_teams_tenant_kod");

                    b.ToTable("teams", "public");
                });

            modelBuilder.Entity("TShift.Domain.Yetki.Izin", b =>
                {
                    b.Property<string>("Kod")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("kod");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("kategori");

                    b.HasKey("Kod");

                    b.ToTable("permissions", "public");

                    b.HasData(
                        new
                        {
                            Kod = "calisan.gor",
                            Aciklama = "Çalışan listesi ve detayını görür",
                            Kategori = "Çalışan"
                        },
                        new
                        {
                            Kod = "calisan.duzenle",
                            Aciklama = "Çalışan ekler ve düzenler",
                            Kategori = "Çalışan"
                        },
                        new
                        {
                            Kod = "sozlesme.duzenle",
                            Aciklama = "Sözleşme bilgisi düzenler",
                            Kategori = "Çalışan"
                        },
                        new
                        {
                            Kod = "yetkinlik.ata",
                            Aciklama = "Çalışana yetkinlik atar",
                            Kategori = "Çalışan"
                        },
                        new
                        {
                            Kod = "izin.gir",
                            Aciklama = "Başkası adına izin girer",
                            Kategori = "İzin"
                        },
                        new
                        {
                            Kod = "izin.talep",
                            Aciklama = "Kendi izin talebini oluşturur",
                            Kategori = "İzin"
                        },
                        new
                        {
                            Kod = "uygunluk.gir",
                            Aciklama = "Uygunluk kaydı girer",
                            Kategori = "İzin"
                        },
                        new
                        {
                            Kod = "kural.parametre",
                            Aciklama = "Kural parametrelerini değiştirir",
                            Kategori = "Kural"
                        },
                        new
                        {
                            Kod = "kural.istisna",
                            Aciklama = "Kural istisnası tanımlar",
                            Kategori = "Kural"
                        },
                        new
                        {
                            Kod = "vardiya.sablon",
                            Aciklama = "Vardiya şablonu tanımlar",
                            Kategori = "Kural"
                        },
                        new
                        {
                            Kod = "talep.gir",
                            Aciklama = "Talep ve kapasite verisi girer",
                            Kategori = "Talep"
                        },
                        new
                        {
                            Kod = "plan.uret",
                            Aciklama = "Plan üretir",
                            Kategori = "Plan"
                        },
                        new
                        {
                            Kod = "plan.duzenle",
                            Aciklama = "Plan düzenler",
                            Kategori = "Plan"
                        },
                        new
                        {
                            Kod = "plan.onayla",
                            Aciklama = "Planı onaylar",
                            Kategori = "Plan"
                        },
                        new
                        {
                            Kod = "plan.yayinla",
                            Aciklama = "Planı yayınlar",
                            Kategori = "Plan"
                        },
                        new
                        {
                            Kod = "gerceklesen.yukle",
                            Aciklama = "Gerçekleşen veri yükler",
                            Kategori = "Rapor"
                        },
                        new
                        {
                            Kod = "rapor.gor",
                            Aciklama = "Raporları görüntüler",
                            Kategori = "Rapor"
                        },
                        new
                        {
                            Kod = "kullanici.yonet",
                            Aciklama = "Kullanıcı ve yetki yönetir",
                            Kategori = "Yönetim"
                        },
                        new
                        {
                            Kod = "denetim.gor",
                            Aciklama = "Denetim kaydını görüntüler",
                            Kategori = "Yönetim"
                        });
                });

            modelBuilder.Entity("TShift.Domain.Yetki.KullaniciKapsami", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("HedefId")
                        .HasColumnType("uuid")
                        .HasColumnName("kapsam_id");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Tip")
                        .HasColumnType("smallint")
                        .HasColumnName("kapsam_tipi");

                    b.HasKey("Id");

                    b.HasIndex("KiraciId");

                    b.HasIndex("KullaniciId", "Tip", "HedefId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_scopes");

                    b.ToTable("user_scopes", "public");
                });

            modelBuilder.Entity("TShift.Domain.Yetki.KullaniciRolu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("GecerlilikBas")
                        .HasColumnType("date")
                        .HasColumnName("gecerlilik_bas");

                    b.Property<DateOnly?>("GecerlilikBitis")
                        .HasColumnType("date")
                        .HasColumnName("gecerlilik_bitis");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("VerenKullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("veren_user_id");

                    b.HasKey("Id");

                    b.HasIndex("KiraciId");

                    b.HasIndex("KullaniciId")
                        .HasDatabaseName("ix_user_roles_user");

                    b.HasIndex("RolId");

                    b.ToTable("user_roles", "public");
                });

            modelBuilder.Entity("TShift.Domain.Yetki.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("ad");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<short>("Kapsam")
                        .HasColumnType("smallint")
                        .HasColumnName("kapsam");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("kod");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("SistemMi")
                        .HasColumnType("boolean")
                        .HasColumnName("sistem_mi");

                    b.HasKey("Id");

                    b.HasIndex("KiraciId", "Kod")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_tenant_kod");

                    b.ToTable("roles", "public");
                });

            modelBuilder.Entity("TShift.Domain.Yetki.RolIzni", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("IzinKodu")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("permission_kod");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("IzinKodu");

                    b.HasIndex("KiraciId");

                    b.HasIndex("RolId", "IzinKodu")
                        .IsUnique()
                        .HasDatabaseName("ux_role_permissions");

                    b.ToTable("role_permissions", "public");
                });

            modelBuilder.Entity("TShift.Domain.Calisanlar.Calisan", b =>
                {
                    b.HasOne("TShift.Domain.Organizasyon.Ekip", null)
                        .WithMany()
                        .HasForeignKey("BirincilEkipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TShift.Domain.Organizasyon.Departman", null)
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Calisanlar.CalisanSozlesmesi", b =>
                {
                    b.HasOne("TShift.Domain.Calisanlar.Calisan", null)
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Denetim.DenetimKaydi", b =>
                {
                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Kimlik.Kullanici", b =>
                {
                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Kimlik.KullaniciKimlikBilgisi", b =>
                {
                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TShift.Domain.Kimlik.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Kimlik.YenilemeJetonu", b =>
                {
                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TShift.Domain.Kimlik.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Organizasyon.Departman", b =>
                {
                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Organizasyon.Ekip", b =>
                {
                    b.HasOne("TShift.Domain.Organizasyon.Departman", null)
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Yetki.KullaniciKapsami", b =>
                {
                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TShift.Domain.Kimlik.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Yetki.KullaniciRolu", b =>
                {
                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TShift.Domain.Kimlik.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TShift.Domain.Yetki.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Yetki.Rol", b =>
                {
                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Yetki.RolIzni", b =>
                {
                    b.HasOne("TShift.Domain.Yetki.Izin", null)
                        .WithMany()
                        .HasForeignKey("IzinKodu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TShift.Domain.Yetki.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
