// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TShift.Infrastructure.Persistence;

#nullable disable

namespace TShift.Infrastructure.Migrations
{
    [DbContext(typeof(TShiftDbContext))]
    [Migration("20260910002040_Ilk")]
    partial class Ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TShift.Domain.Calisanlar.Calisan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ad");

                    b.Property<Guid?>("BirincilEkipId")
                        .HasColumnType("uuid")
                        .HasColumnName("birincil_team_id");

                    b.Property<Guid>("DepartmanId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("DisSistemId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dis_sistem_id");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint")
                        .HasColumnName("durum");

                    b.Property<string>("Eposta")
                        .HasColumnType("citext")
                        .HasColumnName("eposta");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("IseGiris")
                        .HasColumnType("date")
                        .HasColumnName("ise_giris");

                    b.Property<DateOnly?>("IstenCikis")
                        .HasColumnType("date")
                        .HasColumnName("isten_cikis");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("KullaniciId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PersonelNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("personel_no");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("soyad");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefon");

                    b.HasKey("Id");

                    b.HasIndex("BirincilEkipId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("KiraciId", "PersonelNo")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_tenant_personel_no");

                    b.HasIndex("KiraciId", "DepartmanId", "Durum")
                        .HasDatabaseName("ix_employees_tenant_dept_durum");

                    b.ToTable("employees", "public");
                });

            modelBuilder.Entity("TShift.Domain.Calisanlar.CalisanSozlesmesi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<DateOnly>("Baslangic")
                        .HasColumnType("date")
                        .HasColumnName("baslangic");

                    b.Property<DateOnly?>("Bitis")
                        .HasColumnType("date")
                        .HasColumnName("bitis");

                    b.Property<Guid>("CalisanId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("GunlukAzamiSaat")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("gunluk_azami_saat");

                    b.Property<decimal>("HaftalikSaat")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("haftalik_saat");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Tip")
                        .HasColumnType("smallint")
                        .HasColumnName("tip");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId", "Aktif")
                        .HasDatabaseName("ix_contracts_employee_aktif");

                    b.ToTable("employee_contracts", "public");
                });

            modelBuilder.Entity("TShift.Domain.Kimlik.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ad");

                    b.Property<short>("BasarisizGiris")
                        .HasColumnType("smallint")
                        .HasColumnName("basarisiz_giris");

                    b.Property<Guid?>("CalisanId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("DisKimlikId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dis_kimlik_id");

                    b.Property<string>("DisKimlikSaglayici")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("dis_kimlik_saglayici");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint")
                        .HasColumnName("durum");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("eposta");

                    b.Property<bool>("EpostaDogrulandi")
                        .HasColumnType("boolean")
                        .HasColumnName("eposta_dogrulandi");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("KilitBitis")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kilit_bitis");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("MfaAktif")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_aktif");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("SonGiris")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("son_giris");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("soyad");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefon");

                    b.HasKey("Id");

                    b.HasIndex("KiraciId", "Eposta")
                        .IsUnique()
                        .HasDatabaseName("ux_users_tenant_eposta");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("TShift.Domain.Kiracilar.Kiraci", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad");

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("birim_adi");

                    b.Property<DateOnly?>("DenemeBitis")
                        .HasColumnType("date")
                        .HasColumnName("deneme_bitis");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint")
                        .HasColumnName("durum");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<short>("HaftaBaslangic")
                        .HasColumnType("smallint")
                        .HasColumnName("hafta_baslangic");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SektorPaketi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sektor_paketi");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("ZamanDilimi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("zaman_dilimi");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_slug");

                    b.ToTable("tenants", "public");
                });

            modelBuilder.Entity("TShift.Domain.Organizasyon.Departman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AcilisSaat")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("acilis_saat");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<short>("CalismaTipi")
                        .HasColumnType("smallint")
                        .HasColumnName("calisma_tipi");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("KapanisSaat")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("kapanis_saat");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kod");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("UstDepartmanId")
                        .HasColumnType("uuid")
                        .HasColumnName("ust_department_id");

                    b.HasKey("Id");

                    b.HasIndex("KiraciId", "Kod")
                        .IsUnique()
                        .HasDatabaseName("ux_departments_tenant_kod");

                    b.ToTable("departments", "public");
                });

            modelBuilder.Entity("TShift.Domain.Organizasyon.Ekip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<Guid>("DepartmanId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTimeOffset?>("GuncellemeZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("KiraciId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kod");

                    b.Property<DateTimeOffset>("OlusturmaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("KiraciId", "Kod")
                        .IsUnique()
                        .HasDatabaseName("ux_teams_tenant_kod");

                    b.ToTable("teams", "public");
                });

            modelBuilder.Entity("TShift.Domain.Calisanlar.Calisan", b =>
                {
                    b.HasOne("TShift.Domain.Organizasyon.Ekip", null)
                        .WithMany()
                        .HasForeignKey("BirincilEkipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TShift.Domain.Organizasyon.Departman", null)
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Calisanlar.CalisanSozlesmesi", b =>
                {
                    b.HasOne("TShift.Domain.Calisanlar.Calisan", null)
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Kimlik.Kullanici", b =>
                {
                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Organizasyon.Departman", b =>
                {
                    b.HasOne("TShift.Domain.Kiracilar.Kiraci", null)
                        .WithMany()
                        .HasForeignKey("KiraciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TShift.Domain.Organizasyon.Ekip", b =>
                {
                    b.HasOne("TShift.Domain.Organizasyon.Departman", null)
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
