# -*- coding: utf-8 -*-
"""
MUTASYON KOSTURUCU -- elle secilmis bozmalar, TEKRARLANABILIR bicimde

NEDEN VAR (30 Eylul)
  Bu oturumda her yeni kural icin bozmalar elle, satir ici bir betikle
  denendi. O yontemin sessiz bir acigi CIKTI:

    Python derlenmis bytecode'u (__pycache__) gecerli sayarken kaynagin
    DEGISIKLIK ZAMANINA (saniye) ve BOYUTUNA bakar. Bir mutasyon AYNI
    UZUNLUKTA bir degisiklikse (`plan_geceler` -> `plan_gunleri`, ikisi de
    12 harf) ve dosya AYNI SANIYEDE geri yazilirsa, mutasyonlu bytecode
    ozgun kaynak icin de gecerli sayilir.

  Olculdu: `_gecmis_eksik` diskte dogruydu ama Python on ikinci
  mutasyonun bytecode'unu calistiriyordu; dogru bir test kirmizi yandi.
  Ters yon de mumkun: bir mutasyon bir oncekinin bytecode'uyla kosup
  sahte "oldu" ya da sahte "yasadi" verebilir.

BU BETIK NE YAPAR
  * her kosudan once __pycache__ silinir ve bytecode HIC yazilmaz
    (PYTHONDONTWRITEBYTECODE=1)
  * ozgun kod BASTA ve SONDA kosulur; ikisi de yesil olmak ZORUNDA --
    yoksa mutasyon sonuclari anlamsizdir ve betik durur
  * her mutasyondan sonra dosya geri yazilir ve md5 ile dogrulanir
  * capa bulunamazsa ATLANDI yazar -- sessizce gecmez

KOSTURMA
  cd C:\\Users\\PC\\Desktop\\Tshift\\09-motor
  py mutasyon_kostur.py            -> hepsi
  py mutasyon_kostur.py gecmis     -> adinda "gecmis" gecen gruplar
"""

import hashlib
import io
import os
import shutil
import subprocess
import sys

BURASI = os.path.dirname(os.path.abspath(__file__))
KOK = os.path.dirname(BURASI)


def _md5(yol):
    return hashlib.md5(io.open(yol, "rb").read()).hexdigest()


def _onbellegi_sil():
    for kok in (BURASI, os.path.join(KOK, "08-motor-testleri")):
        for dizin, alt, _ in os.walk(kok):
            for a in list(alt):
                if a in ("__pycache__", ".pytest_cache"):
                    shutil.rmtree(os.path.join(dizin, a), ignore_errors=True)
                    alt.remove(a)


def _kostur(test):
    _onbellegi_sil()
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
    p = subprocess.run([sys.executable, "-m", "pytest", test, "-q",
                        "--no-header", "-p", "no:cacheprovider"],
                       cwd=BURASI, env=env, capture_output=True, text=True)
    satirlar = [s for s in p.stdout.strip().splitlines() if s.strip()]
    return p.returncode, (satirlar[-1] if satirlar else p.stderr[-200:])


# (grup, dosya, ad, eski, yeni, test)
K = "dogrulayici/kurallar.py"
D = "dogrulayici/denetle.py"
M = "cozucu/model.py"
C = "cozucu/coz.py"
TS = "cozucu/teshis.py"

MUTASYONLAR = [
    # ---- nitelik kapsamasi (30 Eylul) -- dogrulayici
    ("nitelik", K, "yalniz tam saate bak (ceyregi atla)",
     "    for t, g, an in _talep_anlari(girdi):\n        if ekip is not None and t.get(\"ekip\") != ekip:",
     "    for t, g, an in _talep_hucreleri(girdi):\n        if ekip is not None and t.get(\"ekip\") != ekip:",
     "testler/test_nitelik_kapsamasi.py"),
    ("nitelik", K, "saat listesini yok say",
     "    saat_kumesi = None if saatler is None else {int(s) for s in saatler}",
     "    saat_kumesi = None",
     "testler/test_nitelik_kapsamasi.py"),
    ("nitelik", K, "satirin yasal bayragini yok say",
     "                kod, tanim, ekip=ekip, gun=gun, saat=an, nitelik=aranan,",
     "                kod, tanim, ekip=ekip, gun=gun, saat=an, nitelik=aranan,\n                yasal=False, kabul_edilebilir=True,",
     "testler/test_nitelik_kapsamasi.py"),
    ("nitelik", K, "ekip kadrosu suzgecini yok say",
     "        if ekip is not None and ekip not in (c.get(\"ekipler\") or []):\n            continue",
     "        if False:\n            continue",
     "testler/test_nitelik_kapsamasi.py"),
    ("nitelik", K, "K-41 geri: molayi dus (sahada say)",
     "        varlik = sum(1 for a in ilgili if zaman.atanmis_mi(a, gun, an))",
     "        varlik = sum(1 for a in ilgili if zaman.sahada_mi(a, gun, an))",
     "testler/test_nitelik_kapsamasi.py"),
    # ---- nitelik kapsamasi -- cozucu (T-62)
    ("nitelik", M, "cozucu: saatler yoksa hic saat denetlenmesin",
     "                saat_kumesi = (None if saatler is None\n                               else {int(x) for x in saatler})",
     "                saat_kumesi = ({-1} if saatler is None\n                               else {int(x) for x in saatler})",
     "testler/test_nitelik_kapsamasi.py"),
    ("nitelik", M, "cozucu: nitelik tasiyan yoksa yine kisit yazilsin",
     "                if not uygun:\n                    self.notlar.append(\n                        \"%s: '%s' niteligini tasiyan uygun calisan yok, \"\n                        \"kisit yazilmadi\" % (kod, aranan))\n                    continue\n",
     "",
     "testler/test_nitelik_kapsamasi.py"),
    # ---- motorun kendi metrigi (T-65)
    ("metrik", C, "int() geri gelsin (kesirli siniri kirp)",
     "                   and a[\"gun\"] * 24 + a[\"bas\"] <= an\n                   < a[\"gun\"] * 24 + a[\"bit\"])",
     "                   and a[\"gun\"] * 24 + int(a[\"bas\"]) <= an\n                   < a[\"gun\"] * 24 + int(a[\"bit\"]))",
     "testler/test_motor_metrigi.py"),
    # ---- gece vardiyasi azami (K-26) -- dogrulayici
    ("gece_azami", K, "brut olc (molayi dusme)",
     "    return brut - mola\n", "    return brut\n",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "butun molalari dus (pencere disi dahil)",
     "    mola = sum(_kesisim(m0, m1, w0, w1)\n               for m0, m1 in zaman.mola_araliklari(atama))",
     "    mola = sum(m1 - m0 for m0, m1 in zaman.mola_araliklari(atama))",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "pencere gun sinirini asmasin (Z-5)",
     "        bit = zaman.mutlak(gun + (1 if pencere_bit <= pencere_bas else 0),\n                           pencere_bit)",
     "        bit = zaman.mutlak(gun, 24.0)",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "istisnayi hic uygulama",
     "            if istisnali_sektor and _gece_onayi_gecerli(c, girdi, gun):\n                continue",
     "            if False:\n                continue",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "yalniz sektore bak",
     "            if istisnali_sektor and _gece_onayi_gecerli(c, girdi, gun):",
     "            if istisnali_sektor:",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "yalniz onaya bak",
     "            if istisnali_sektor and _gece_onayi_gecerli(c, girdi, gun):",
     "            if _gece_onayi_gecerli(c, girdi, gun):",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "sinirda esitlik ihlal (>=)",
     "            if gece > azami + 1e-9:", "            if gece >= azami:",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "suresi gecmis onay gecerli",
     "        return date.fromisoformat(bitis) >= gece", "        return True",
     "testler/test_gece_vardiyasi_azami.py"),
    # ---- gece vardiyasi azami -- cozucu
    ("gece_azami", M, "cozucu: kisit yazilmasin",
     "                    if (c[\"id\"], d, t[\"id\"]) in self.x:\n                        self.m.Add(self.x[(c[\"id\"], d, t[\"id\"])] == 0)\n\n    def _izin(self):",
     "                    pass\n\n    def _izin(self):",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", M, "cozucu: istisna hic uygulanmasin",
     "                if istisnali and _gece_onayi_var(c, self.girdi, d):\n                    continue",
     "                if False:\n                    continue",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", M, "cozucu: yalniz onaya bak",
     "                if istisnali and _gece_onayi_var(c, self.girdi, d):",
     "                if _gece_onayi_var(c, self.girdi, d):",
     "testler/test_gece_vardiyasi_azami.py"),
    # ---- firma sinirlari -- dogrulayici
    ("firma", K, "asgari sure: net olc",
     "        bas, bit = zaman.aralik(a)\n        sure = bit - bas\n        if sure < asgari - 1e-9:",
     "        sure = zaman.net_saat(a)\n        if sure < asgari - 1e-9:",
     "testler/test_firma_sinirlari.py"),
    ("firma", K, "asgari sure: esitlik ihlal (<=)",
     "        if sure < asgari - 1e-9:", "        if sure <= asgari:",
     "testler/test_firma_sinirlari.py"),
    ("firma", K, "ardisik gece: calisma gunu say",
     "        geceler = {a[\"gun\"] for a in liste\n                   if _atama_gece_mi(girdi, a, sablonlar)}",
     "        geceler = {a[\"gun\"] for a in liste}",
     "testler/test_firma_sinirlari.py"),
    ("firma", M, "cozucu: gece kisiti yok",
     "                if terim:\n                    self.m.Add(sum(terim) <= azami)",
     "                pass",
     "testler/test_firma_sinirlari.py"),
    ("firma", M, "cozucu: kisa sablon serbest",
     "                    if (c[\"id\"], d, t[\"id\"]) in self.x:\n                        self.m.Add(self.x[(c[\"id\"], d, t[\"id\"])] == 0)\n\n    # ---- kapsama",
     "                    pass\n\n    # ---- kapsama",
     "testler/test_firma_sinirlari.py"),
    # ---- gecmis veri (T-28, K-42) -- dogrulayici
    ("gecmis", K, "gecmis listeye eklenmesin",
     "        liste.extend(_gecmis_kayitlari(girdi, kimlik))", "        pass",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "dinlenme: gecmis-gecmis cifti atlanmasin",
     "            if sonraki.get(\"_gecmis\"):\n                continue                      # gecmis kendi icinde",
     "            if False:\n                continue",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "cakisma: karisik cift de atlansin",
     "                if liste[i].get(\"_gecmis\") and liste[j].get(\"_gecmis\"):\n                    continue\n                ort",
     "                if liste[i].get(\"_gecmis\") or liste[j].get(\"_gecmis\"):\n                    continue\n                ort",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "tatil: gecmisteki pencere atlanmasin",
     "            if bas + pencere - 1 < 0:\n                continue                      # tamamen gecmiste",
     "            if False:\n                continue",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "seri: gecmisteki seri de sayilsin",
     "            if seri and g - 1 >= 0 and seri > en_uzun:",
     "            if seri and seri > en_uzun:",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "gun>=0 kaydi da gecmis sayilsin",
     "        if gun is None or bas is None or bit is None or gun >= 0:",
     "        if gun is None or bas is None or bit is None:",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "bilinen gunler listesi yok sayilsin",
     "    return ({g for g in (c.get(\"gecmis_bilinen_gunler\") or []) if g < 0}\n            | {k[\"gun\"] for k in kayitlar})",
     "    return {k[\"gun\"] for k in kayitlar}",
     "testler/test_gecmis_veri.py"),
    ("gecmis", D, "geri yuruyus bilinen bos gunde durmasin",
     "        elif d in bilinen:\n            return \"guvenli\", None",
     "        elif False:\n            return \"guvenli\", None",
     "testler/test_gecmis_veri.py"),
    ("gecmis", D, "kanitli ihlal de raporlansin",
     "            if k + plan_serisi >= esik:\n                return \"ihlal\", None",
     "            if k + plan_serisi >= esik:\n                return \"belirsiz\", d",
     "testler/test_gecmis_veri.py"),
    ("gecmis", D, "pazartesi bossa da raporlansin",
     "        if (\"VARDIYA_ARASI_DINLENME\" in aktif and 0 in plan_gunleri\n                and -1 not in bilinen):",
     "        if (\"VARDIYA_ARASI_DINLENME\" in aktif\n                and -1 not in bilinen):",
     "testler/test_gecmis_veri.py"),
    ("gecmis", D, "gece raporu pazartesi gece degilse de",
     "                                    _plan_serisi(plan_geceler), esik)",
     "                                    _plan_serisi(plan_gunleri), esik)",
     "testler/test_gecmis_veri.py"),
    # ---- gecmis veri -- cozucu
    ("gecmis", M, "cozucu: pazartesi dinlenme siniri yazilmasin",
     "                        if (d * 24 + t[\"bas\"] - bitis < asgari\n                                and (c[\"id\"], d, t[\"id\"]) in self.x):\n                            self.m.Add(self.x[(c[\"id\"], d, t[\"id\"])] == 0)",
     "                        pass",
     "testler/test_gecmis_veri.py"),
    ("gecmis", M, "cozucu: ardisik gun gecmis penceresi yazilmasin",
     "                plan = range(0, min(HAFTA_GUN, bas + azami + 1))\n                self.m.Add(sabit + sum(self._calisiyor(c[\"id\"], d)\n                                       for d in plan) <= azami)",
     "                pass",
     "testler/test_gecmis_veri.py"),
    ("gecmis", M, "cozucu: ardisik gece gecmis penceresi yazilmasin",
     "                if terim:\n                    self.m.Add(sabit + sum(terim) <= azami)",
     "                pass",
     "testler/test_gecmis_veri.py"),
    ("gecmis", M, "cozucu: gecmisi HIC okumasin",
     "    cikan = []\n    for k in calisan.get(\"gecmis_vardiyalar\") or []:",
     "    cikan = []\n    for k in []:",
     "testler/test_gecmis_veri.py"),
    ("gecmis", M, "cozucu: gun>=0 kaydi da gecmis sayilsin",
     "        if gun is None or bas is None or bit is None or gun >= 0:\n            continue\n        bas, bit = float(bas), float(bit)",
     "        if gun is None or bas is None or bit is None:\n            continue\n        bas, bit = float(bas), float(bit)",
     "testler/test_gecmis_veri.py"),
    # ---- gece tespiti: isaretsiz tahmin (T-69), adalet boyutu (T-71)
    ("gece_tespiti", K, 'adalet: sablon isaretine bakma',
     '        return lambda a: _atama_gece_mi(girdi, a, sablonlar)',
     '        return lambda a: _atama_gece_mi({}, a, {})',
     'testler/test_gece_tespiti.py'),
    ("gece_tespiti", K, 'adalet: girdi sayaca gecmesin',
     '        sayac = _boyut_sayaci(boyut, girdi)',
     '        sayac = _boyut_sayaci(boyut)',
     'testler/test_gece_tespiti.py'),
    # ---- sahte PDKS uretici (30 Eylul aksami) -- olcum aracinin kendisi
    ("pdks", '../08-motor-testleri/gercekci-veri-seti/sahte_pdks.py', 'yakalanan gerceklesende olmayan kayit icersin',
     '            k for k in yasanan if rnd.random() < ayar["kayit_orani"]]',
     '            k for k in yasanan if rnd.random() < ayar["kayit_orani"]] + [\n            {"gun": -1, "bas": 1, "bit": 2}]',
     '../08-motor-testleri/gercekci-veri-seti/testler/test_sahte_pdks.py'),
    ("pdks", '../08-motor-testleri/gercekci-veri-seti/sahte_pdks.py', 'bilinen gun = planli gun',
     '        bilinen[kimlik] = sorted({k["gun"] for k in yakalanan})',
     '        bilinen[kimlik] = sorted({a["gun"] - kaydir for a in kisiye.get(kimlik, [])})',
     '../08-motor-testleri/gercekci-veri-seti/testler/test_sahte_pdks.py'),
    ("pdks", '../08-motor-testleri/gercekci-veri-seti/sahte_pdks.py', 'uyum orani yok sayilsin',
     '            if r < ayar["uyum"]:',
     '            if r < 0.5:',
     '../08-motor-testleri/gercekci-veri-seti/testler/test_sahte_pdks.py'),
    ("pdks", '../08-motor-testleri/gercekci-veri-seti/sahte_pdks.py', 'kayda gece isareti eklensin',
     '            yasanan.append({"gun": a["gun"] - kaydir, "bas": bas, "bit": bit})',
     '            yasanan.append({"gun": a["gun"] - kaydir, "bas": bas, "bit": bit,\n                            "gece": False})',
     '../08-motor-testleri/gercekci-veri-seti/testler/test_sahte_pdks.py'),
    ("pdks", '../08-motor-testleri/gercekci-veri-seti/sahte_pdks.py', 'cakisma dinlenme satiriyla eslenmesin',
     'HABERCI = {"CAKISMA_YOK": "VARDIYA_ARASI_DINLENME"}',
     'HABERCI = {}',
     '../08-motor-testleri/gercekci-veri-seti/testler/test_sahte_pdks.py'),
    # ---- sure butcesi (T-59, 30 Eylul aksami)
    ("butce", C, 'birinci asama eski butcesini alsin',
     '        c.parameters.max_time_in_seconds = _ilk_asama_payi(ayar)',
     '        c.parameters.max_time_in_seconds = float(ayar.get("ilk_asama_saniye", 120))',
     'testler/test_sure_butcesi.py'),
    ("butce", C, 'ana cozum butcenin tamamini alsin',
     '    ana_butce = max(1.0, float(ayar["azami_saniye"]) - ilk_asama)',
     '    ana_butce = float(ayar["azami_saniye"])',
     'testler/test_sure_butcesi.py'),
    ("butce", C, 'ana cozume sifir kalabilsin',
     '    ana_butce = max(1.0, float(ayar["azami_saniye"]) - ilk_asama)',
     '    ana_butce = max(0.0, float(ayar["azami_saniye"]) - ilk_asama)',
     'testler/test_sure_butcesi.py'),
    ("butce", C, 'durma sebebi eski kiyasla',
     '    if butce is None:\n        butce = ayar["azami_saniye"]',
     '    butce = ayar["azami_saniye"]',
     'testler/test_sure_butcesi.py'),
    # ---- 30 Eylul gecesi: K-43 isaret tabani, K-44 yasal gece siniri,
    #      K-45 gece haftasi, K-46 hafta sonu, K-47 ozet, T-76 teshis
    ('isaret', K, 'K-43 geri: isaret her yonde ezsin (dogrulayici)',
     '        return (yasal or bool(sablon["gece_vardiyasi"])), False\n    return yasal, True',
     '        return bool(sablon["gece_vardiyasi"]), False\n    return yasal, True',
     'testler/test_gece_uygunlugu.py'),
    ('isaret', K, 'K-43 geri: isaret yok sayilsin (dogrulayici)',
     '        return (yasal or bool(sablon["gece_vardiyasi"])), False\n    return yasal, True',
     '        return yasal, False\n    return yasal, True',
     'testler/test_gece_tespiti.py'),
    ('isaret', K, 'K-43 geri: gecmis kaydin isareti ezsin',
     '        if "_gece" in a:\n            return yasal or bool(a["_gece"])\n        return yasal',
     '        if "_gece" in a:\n            return bool(a["_gece"])\n        return yasal',
     'testler/test_gecmis_veri.py'),
    ('isaret', M, 'K-43 geri: isaret her yonde ezsin (cozucu)',
     '        return (yasal or bool(sablon["gece_vardiyasi"])), False\n    return yasal, True',
     '        return bool(sablon["gece_vardiyasi"]), False\n    return yasal, True',
     'testler/test_gece_uygunlugu.py'),
    ('isaret', M, 'K-43 geri: cozucu gecmis kaydin isareti ezsin',
     '    return _yasal_gece_postasi(bas, bit) or bool(isaret)',
     '    return bool(isaret) if isaret is not None else _yasal_gece_postasi(bas, bit)',
     'testler/test_gecmis_veri.py'),
    ('isaret', M, 'ezilen isaret notu yazilmasin',
     '            elif gece and not t.get("gece_vardiyasi"):\n                ezilenler.append(t["id"])',
     '            elif False:\n                ezilenler.append(t["id"])',
     'testler/test_gece_uygunlugu.py'),
    ('gece_tespiti', K, 'tahmin: eski olcu (ayni gun, en ufak degme)',
     '    yasal = _yasal_gece_postasi_mi(\n        {"gun": 0, "bas": sablon["bas"], "bit": sablon["bit"]})',
     '    yasal = (min(float(sablon["bit"]), 30.0) - max(float(sablon["bas"]), 20.0) > 0)',
     'testler/test_gece_tespiti.py'),
    ('gece_tespiti', M, 'cozucu tahmin: eski olcu (ayni gun, en ufak degme)',
     '    yasal = _yasal_gece_postasi(sablon["bas"], sablon["bit"])\n    if "gece_vardiyasi" in sablon:',
     '    yasal = (min(float(sablon["bit"]), 30.0) - max(float(sablon["bas"]), 20.0) > 0)\n    if "gece_vardiyasi" in sablon:',
     'testler/test_gece_tespiti.py'),
    ('gece_azami', K, 'K-44 geri: posta olcusu yazilmasin',
     '            net = zaman.net_saat(a)\n            if net > azami + 1e-9:',
     '            net = zaman.net_saat(a)\n            if False:',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'K-44: posta olcusu brut olsun',
     '            net = zaman.net_saat(a)\n            if net > azami + 1e-9:',
     '            net = zaman.brut_saat(a)\n            if net > azami + 1e-9:',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'K-44: istisna posta olcusunde uygulanmasin',
     '            if istisnali_sektor and _gece_onayi_gecerli(c, girdi, a["gun"]):\n                continue\n            net',
     '            if False:\n                continue\n            net',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'K-44: ayni vardiya iki kez yazilsin (V-1 yok)',
     '            if any(_kesisim(b0, b1, w0, w1) > 0 for b0, b1 in yazilan):\n                continue',
     '            if False:\n                continue',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'yasal gece: yarisi da gece sayilsin',
     '    return 2 * gece > (bit - bas) + 1e-9\n\n\n# Yonetmelik md. 8/3',
     '    return 2 * gece >= (bit - bas) - 1e-9\n\n\n# Yonetmelik md. 8/3',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'yasal gece: en ufak ortusme yeter',
     '    return 2 * gece > (bit - bas) + 1e-9\n\n\n# Yonetmelik md. 8/3',
     '    return gece > 0\n\n\n# Yonetmelik md. 8/3',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'yasal gece: onceki gecenin donemine bakma',
     '    for d in (gun - 1, gun, gun + 1):\n        w0 = zaman.mutlak(d, p_bas)',
     '    for d in (gun, gun + 1):\n        w0 = zaman.mutlak(d, p_bas)',
     'testler/test_gece_tespiti.py'),
    ('gece_azami', M, 'cozucu K-44 geri: posta suzgeci yazilmasin',
     '        asanlar = asanlar + [(t, _net_saat(t)) for t in yasal_asanlar]',
     '        asanlar = asanlar + []',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', M, 'cozucu K-44: brut olcsun',
     '                         and _net_saat(t) > azami + 1e-9\n',
     '                         and (float(t["bit"]) - float(t["bas"])) > azami + 1e-9\n',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', M, 'cozucu yasal gece: en ufak ortusme yeter',
     '    return 2 * gece > (bit - bas) + 1e-9\n\n\ndef _net_saat(sablon):',
     '    return gece > 0\n\n\ndef _net_saat(sablon):',
     'testler/test_hafta_kurallari.py'),
    ('gece_azami', M, 'cozucu yasal gece: yarisi da gece sayilsin',
     '    return 2 * gece > (bit - bas) + 1e-9\n\n\ndef _net_saat(sablon):',
     '    return 2 * gece >= (bit - bas) - 1e-9\n\n\ndef _net_saat(sablon):',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', M, 'cozucu yasal gece: onceki gece yok',
     '    for w0 in (-4.0, 20.0, 44.0):',
     '    for w0 in (20.0, 44.0):',
     'testler/test_gece_tespiti.py'),
    ('hafta', K, 'hafta: sifira dogru yuvarla (int)',
     'def _hafta(gun):\n    return gun // 7',
     'def _hafta(gun):\n    return int(gun / 7)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'gece haftasi: yarisi da yeter (>=)',
     '    return 2 * gece_saat > toplam + 1e-9',
     '    return 2 * gece_saat >= toplam - 1e-9',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'gece haftasi: vardiya sayisiyla olc',
     '    gece_saat = sum(zaman.brut_saat(a) for a in gece)\n    toplam = sum(zaman.brut_saat(a) for a in hafta_listesi)',
     '    gece_saat = len(gece)\n    toplam = len(hafta_listesi)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'gece haftasi: asgari_gece yok sayilsin',
     '    if asgari_gece is not None and len(gece) >= int(asgari_gece) > 0:\n        return True\n    gece_saat',
     '    if False:\n        return True\n    gece_saat',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'gecmis hafta: yarim bilinen hafta da degerlendirilsin',
     '            if h < 0 and _hafta_tam_bilinen_mi(h, bilinen)\n            and _gece_haftasi_mi(hl, asgari_gece)}',
     '            if h < 0\n            and _gece_haftasi_mi(hl, asgari_gece)}',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'devri: pencere kesintisiz seri olsun (G-G-D-G serbest)',
     '            sayi = sum(1 for h in range(hafta - pencere + 1, hafta + 1)\n                       if h in gece_haftalari)',
     '            sayi = _geriye_seri(gece_haftalari, hafta)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'devri: sinirda esitlik ihlal (>=)',
     '            if sayi > azami:\n                geceler = [a for a in haftalar[hafta]',
     '            if sayi >= azami:\n                geceler = [a for a in haftalar[hafta]',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'devri: ust sinir kirpilmasin',
     '    return max(1, min(verilen, GECE_HAFTASI_YASAL_UST_SINIR)), verilen',
     '    return max(1, verilen), verilen',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'devri: gecmis okunmasin',
     '    for kimlik, liste in sorted(_kisiye_gore_gecmisli(girdi, atamalar).items()):\n        haftalar = _haftaya_gore(liste)',
     '    for kimlik, liste in sorted(_kisiye_gore(atamalar).items()):\n        haftalar = _haftaya_gore(liste)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'devri: K-40 isaretine bak (firma tanimi)',
     '    gece = [a for a in hafta_listesi if _yasal_gece_postasi_mi(a)]',
     '    gece = [a for a in hafta_listesi if _atama_gece_mi({}, a, {})]',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'cogunluk gunu: baslangic gunu olsun',
     '    return a["gun"] + 1 if 2 * tasan > (bit - bas) + 1e-9 else a["gun"]',
     '    return a["gun"]',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'cogunluk gunu: en ufak tasma ertesi gun',
     '    return a["gun"] + 1 if 2 * tasan > (bit - bas) + 1e-9 else a["gun"]',
     '    return a["gun"] + 1 if tasan > 0 else a["gun"]',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'hsonu: tek gun yeter',
     '        tam = {h for h, g in gunler.items() if g >= {5, 6}}',
     '        tam = {h for h, g in gunler.items() if g}',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'hsonu: sinirda esitlik ihlal (>=)',
     '            if seri > azami:\n                ilk = min(_cogunluk_gunu(a) for a in liste',
     '            if seri >= azami:\n                ilk = min(_cogunluk_gunu(a) for a in liste',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'hsonu: gecmis okunmasin',
     '    for kimlik, liste in sorted(_kisiye_gore_gecmisli(girdi, atamalar).items()):\n        gunler = _calisilan_hafta_sonu_gunleri(liste)',
     '    for kimlik, liste in sorted(_kisiye_gore(atamalar).items()):\n        gunler = _calisilan_hafta_sonu_gunleri(liste)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'adalet hafta sonu: baslangic gunuyle',
     '        return lambda a: _hafta_sonu_gunu(a) is not None',
     '        return lambda a: a["gun"] in (5, 6)',
     'testler/test_gece_tespiti.py'),
    ('hafta', D, 'rapor devri: kanitli ihlal de raporlansin',
     '                if (len(kanitli) < azami\n                        and len(kanitli) + len(bilinmeyen) >= azami):',
     '                if len(kanitli) + len(bilinmeyen) >= azami:',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'rapor devri: bilinmeyen yetmese de raporlansin',
     '                if (len(kanitli) < azami\n                        and len(kanitli) + len(bilinmeyen) >= azami):',
     '                if len(kanitli) < azami and bilinmeyen:',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'rapor devri: bu hafta gece haftasi degilken de',
     '            if kurallar._gece_haftasi_mi(haftalar.get(0, []), asgari_gece):\n                azami, _ = kurallar._gece_haftasi_azami(tanim)',
     '            if True:\n                azami, _ = kurallar._gece_haftasi_azami(tanim)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'rapor hsonu: bilinen bos hafta sonunda durmasin',
     '                    if 7 * h + 5 in bilinen and 7 * h + 6 in bilinen:\n                        break                   # bilinen, tam calisilmamis',
     '                    if False:\n                        break',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'rapor hsonu: kanitli olan da raporlansin',
     '                    if gunler.get(h, set()) >= {5, 6}:\n                        continue                # kanitli',
     '                    if False:\n                        continue',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'rapor hsonu: plan tek gunken de',
     '            if gunler.get(0, set()) >= {5, 6}:\n                azami = int(kurallar._p(aktif["ARDISIK_HAFTA_SONU_LIMIT"],',
     '            if gunler.get(0, set()):\n                azami = int(kurallar._p(aktif["ARDISIK_HAFTA_SONU_LIMIT"],',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'ust sinir raporu yazilmasin',
     '            if verilen != azami:\n                eksik.append({',
     '            if False:\n                eksik.append({',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: kisit yazilmasin',
     '            if gece_terim:\n                self.m.Add(2 * sum(gece_terim) <= sum(toplam_terim))',
     '            if False:\n                self.m.Add(2 * sum(gece_terim) <= sum(toplam_terim))',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: esitlik de yasak (<)',
     '                self.m.Add(2 * sum(gece_terim) <= sum(toplam_terim))',
     '                self.m.Add(2 * sum(gece_terim) < sum(toplam_terim))',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: asgari_gece kisiti yazilmasin',
     '                if asgari_gece is not None and int(asgari_gece) > 0:\n                    self.m.Add(sum(gece_sayi) <= int(asgari_gece) - 1)',
     '                pass',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: kanitli sayisi esikten dusukken de',
     '            if kanitli < azami:\n                continue\n            gece_terim',
     '            if kanitli < 0:\n                continue\n            gece_terim',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: ust sinir kirpilmasin',
     '        azami = max(1, min(verilen, 2))',
     '        azami = max(1, verilen)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: yarim bilinen hafta degerlendirilsin',
     '        if not all(d in bilinen for d in range(7 * hafta, 7 * hafta + 7)):\n            return False',
     '        if False:\n            return False',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: gecmis gece haftasi vardiya sayisiyla',
     '        gece_saat = sum(b1 - b0 for b0, b1 in gece)\n        toplam = sum(b1 - b0 for _, b0, b1 in kayitlar)',
     '        gece_saat = len(gece)\n        toplam = len(kayitlar)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: gecmiste yarisi da yeter',
     '        return 2 * gece_saat > toplam + 1e-9',
     '        return 2 * gece_saat >= toplam - 1e-9',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: hafta sifira yuvarlansin',
     '                    if g // 7 == hafta]',
     '                    if int(g / 7) == hafta]',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: pencere yerine yalniz gecen hafta',
     '            kanitli = sum(1 for h in range(-(2 * azami - 1), 0)',
     '            kanitli = sum(1 for h in range(-1, 0)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu hsonu: kisit yazilmasin',
     '            for x1 in cumartesi:\n                for x2 in pazar:\n                    self.m.Add(x1 + x2 <= 1)',
     '            pass',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu hsonu: tek gun yeter (gecmis)',
     '        return gunler >= {5, 6}',
     '        return bool(gunler)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu hsonu: bir hafta yetsin',
     '            if not all(self._hafta_sonu_gecmiste_tam(c, h)\n                       for h in range(-1, -azami - 1, -1)):',
     '            if not all(self._hafta_sonu_gecmiste_tam(c, h)\n                       for h in range(-1, -2, -1)):',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cogunluk kaymasi: hep baslangic gunu',
     '    return 1 if 2 * tasan > (bit - bas) + 1e-9 else 0',
     '    return 0',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cogunluk kaymasi: en ufak tasma',
     '    return 1 if 2 * tasan > (bit - bas) + 1e-9 else 0',
     '    return 1 if tasan > 0 else 0',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu adalet hafta sonu: baslangic gunuyle',
     '            return lambda t, d: _hafta_sonu_gunu(d, t["bas"], t["bit"]) is not None',
     '            return lambda t, d: d in (5, 6)',
     'testler/test_hafta_kurallari.py'),
    ('rapor', D, 'ozet: yasal bayragi okunmasin',
     '        if yasal.get(x["kural"]):\n            k["yasal"] = True',
     '        pass',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    ('rapor', D, 'ozet: siralama yasal one almasin',
     '    liste.sort(key=lambda k: (not k["yasal"], k["calisan"]))',
     '    liste.sort(key=lambda k: k["calisan"])',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    ('rapor', D, 'ozet: kisi sayisi satir sayisi olsun',
     '        "kisi": len(liste),',
     '        "kisi": len(gecmis_eksik),',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    ('teshis', TS, "T-76 geri: sure asimi 'engellemiyor' sayilsin",
     '        elif durum is None:\n            belirsiz.append(dict(satir, deneme_saniye=saniye))',
     '        elif False:\n            belirsiz.append(dict(satir, deneme_saniye=saniye))',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    ('teshis', TS, 'T-76: kural basina butce sabit 10',
     '    saniye = float((ayar or {}).get("teshis_kural_saniye", 10))',
     '    saniye = 10.0',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    ('teshis', TS, 'T-76: not yazilmasin',
     '    if not engelleyen and belirsiz:\n        cevap["teshis"]["not"] = (',
     '    if False:\n        cevap["teshis"]["not"] = (',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    # ---- T-78 (1 Ekim): ceyrege sigmayan mola -- her degisiklik tek tek geri
    ('mola_t78', M, 'T-78 geri: pencere araligi round ile',
     '    sure_q = _ceyrek_yukari(sure)\n',
     '    sure_q = int(round(sure * CEYREK))\n',
     'testler/test_net_saat_uyumu.py'),
    ('mola_t78', M, 'T-78 geri: dilim kumesi bitisi round ile',
     '    return list(range(_q(gun, baslangic),\n                      _q(gun, baslangic) + _ceyrek_yukari(dk / 60.0)))',
     '    return list(range(_q(gun, baslangic), _q(gun, baslangic + dk / 60.0)))',
     'testler/test_net_saat_uyumu.py'),
    # Not: "yemek-dinlenme cakismasi ceyrek kumesiyle" mutasyonu ESDEGER
    # cikti ve listeye alinmadi: dilim kumesi yukari yuvarlandigi icin ceyrek
    # kesisimi ile gercek kesisim ayni cevabi veriyor (baslangiclar izgarada).
    ('mola_t78', M, 'T-78: yemek-dinlenme kisiti hic yazilmasin',
     '                    if _gercek_kesisiyor(s, sure, sy, yemek_sure):',
     '                    if False:',
     'testler/test_net_saat_uyumu.py'),
    ('mola_t78', M, 'T-78: emniyet kemeri kaldirilsin (pencere de round)',
     '            onceki = [(i, s) for s in adaylar]',
     '            onceki = []',
     'testler/test_net_saat_uyumu.py'),
    ('mola_t78', M, 'T-78: yukari yuvarlama asagi olsun',
     '    return int(math.ceil(saat * CEYREK - 1e-9))',
     '    return int(math.floor(saat * CEYREK + 1e-9))',
     'testler/test_net_saat_uyumu.py'),
    ('mola_t78', M, 'T-78: gercek kesisim ucu uca degeni de kesisim saysin',
     '    return bas1 < bas2 + sure2_sa - 1e-9 and bas2 < bas1 + sure1_sa - 1e-9',
     '    return bas1 <= bas2 + sure2_sa + 1e-9 and bas2 <= bas1 + sure1_sa + 1e-9',
     'testler/test_net_saat_uyumu.py'),
    # ---- T-60 (1 Ekim): birinci asama molalari sabitler, ipucu tam
    ('ilk_asama', C, 'T-60: molalar sabitlenmesin (eski birinci asama)',
     '    sabitlenen = _molalari_sabitle(kuruldu) if ayar.get("ilk_asama_sabit_mola", True) else []',
     '    sabitlenen = []',
     'testler/test_ilk_asama.py'),
    ('ilk_asama', C, 'T-60: alanlar geri acilmasin',
     '        _molalari_serbest_birak(kuruldu, sabitlenen)\n        amaci_geri_koy()',
     '        amaci_geri_koy()',
     'testler/test_ilk_asama.py'),
    ('ilk_asama', C, 'T-60: ipucu yalniz x icin yazilsin (eski yarim ipucu)',
     '    proto.solution_hint.vars.extend(list(range(len(degerler))))\n    proto.solution_hint.values.extend(degerler)',
     '    proto.solution_hint.vars.extend([v.Index() for v in kuruldu.x.values()])\n    proto.solution_hint.values.extend([degerler[v.Index()] for v in kuruldu.x.values()])',
     'testler/test_ilk_asama.py'),
    ('ilk_asama', M, 'T-60: sabit secim yemekle cakismaya bakmasin',
     "                     if not (sy is not None and _gercek_kesisiyor(s_, sure, sy, ysure))\n",
     "                     if True\n",
     'testler/test_ilk_asama.py'),
    ('ilk_asama', M, 'T-60: sabit secim ideale degil ilk adaya gitsin',
     '            sec = min(uygun, key=lambda s_: (abs(s_ - ideal), s_))',
     '            sec = uygun[0]',
     'testler/test_ilk_asama.py'),
    ('ilk_asama', C, 'T-60: sabitleme yemegi atlasin',
     '        if sy is not None and s is not None and s != sy:\n            sabitlenen.append(v.Index())',
     '        if False:\n            sabitlenen.append(v.Index())',
     'testler/test_ilk_asama.py'),
    # ---- T-21 / K-50 (1 Ekim): cok ekipli calisan kime sayilir
    ('cok_ekipli', M, 'K-50: hepsi modu da tek gibi saysin',
     '        if self.cok_ekipli_sayim == "tek":\n            return self._atama_ekibi(c, t) == ekip\n        return ekip in (c.get("ekipler") or [])',
     '        return self._atama_ekibi(c, t) == ekip',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', M, 'K-50: tek modu da hepsi gibi saysin',
     '        if self.cok_ekipli_sayim == "tek":\n            return self._atama_ekibi(c, t) == ekip\n        return ekip in (c.get("ekipler") or [])',
     '        return ekip in (c.get("ekipler") or [])',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', K, 'K-50 dogrulayici: tek modda da uyelige saysin',
     '    if mod != "hepsi":\n        return False\n    return ekip in uyelik.get(atama.get("calisan"), ())',
     '    return ekip in uyelik.get(atama.get("calisan"), ())',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', K, 'K-50 dogrulayici: hepsi modda da yalniz atamanin ekibi',
     '    if mod != "hepsi":\n        return False\n    return ekip in uyelik.get(atama.get("calisan"), ())',
     '    return False',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', K, 'K-50 dogrulayici: nitelik kapsamasi atamanin ekibine baksin (eski)',
     '              and ekibe_sayilir(a, ekip, uyelik, mod)]',
     '              and (ekip is None or a.get("ekip") == ekip)]',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', D, 'K-50: baska ekipten kapsama sayilmasin',
     '        if sayi > kendi:\n            baska_hucre += 1',
     '        if False:\n            baska_hucre += 1',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', C, 'K-50: cikti ilk ekibi yazsin (eski)',
     '        ekip = kuruldu._atama_ekibi(kisi or {}, sablon)',
     '        ekip = (kisi or {}).get("ekipler", [None])[0]',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', TS, 'K-50: on kontrol baska ekibin sablonunu gormesin (eski)',
     '                if not hepsi or not any(',
     '                if True or not any(',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', TS, 'K-50: teshis mumkun sayisi ekip suzgecsiz (eski)',
     '            if not kuruldu._sayilir(c, t, ekip):\n                continue\n',
     '',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', M, 'K-50: nitelik toplaminda ekip suzgeci kalksin',
     '                           if (ekip is None or self._sayilir(c, t, ekip))\n                           and dilim in _dilimler(d, t["bas"], t["bit"])]',
     '                           if dilim in _dilimler(d, t["bas"], t["bit"])]',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', M, 'K-50: tek modda ekipsiz sablon notu yazilmasin',
     '        if self.cok_ekipli_sayim == "tek":\n            for t in self.sablonlar:',
     '        if False:\n            for t in self.sablonlar:',
     'testler/test_cok_ekipli.py'),
    # ---- T-18 / K-49 (1 Ekim): "bakamadim" kapidan gecemez
    ('kapi', D, 'K-49: kapi denetlenemeyeni gormesin (eski)',
     '        "yayin_kapisi": yayin_kapisi(ihlaller, girdi, uygulanmayan, eksik_boyutlar),',
     '        "yayin_kapisi": yayin_kapisi(ihlaller),',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    ('kapi', D, 'K-49: yasal da kabul bekleyen olsun',
     '    elif yasal:\n        etki = "engelliyor"',
     '    elif False:\n        etki = "engelliyor"',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    ('kapi', D, 'K-49: gerekcesiz kabul de kabul sayilsin',
     '        if (k.get("gerekce") or "").strip():\n            kabuller[k.get("kod")] = k',
     '        kabuller[k.get("kod")] = k',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    ('kapi', D, 'K-49: yumusak da kabul beklesin',
     '    if not sert:\n        etki = "rapor"',
     '    if False:\n        etki = "rapor"',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    ('kapi', D, 'K-49: kirpma raporu da bakamadim sayilsin',
     '        if not e.get("denetlenemedi"):\n            continue',
     '        if False:\n            continue',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    ('kapi', D, 'K-49: kabul bekleyen denetlenemeyen yayini acik biraksin',
     '        "yayinlanabilir": not acik_sert and not d_engelleyen and not d_bekleyen,',
     '        "yayinlanabilir": not acik_sert and not d_engelleyen,',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    # ---- YILLIK_FAZLA_MESAI_TAVANI (1 Ekim) -- iki taraf
    ('yillik', K, 'yillik: tavana esit de ihlal olsun (>=)',
     '        if fazla > 0 and float(yil) + fazla > azami + 1e-9:',
     '        if fazla > 0 and float(yil) + fazla >= azami - 1e-9:',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', K, 'yillik: fazla mesai yokken de yazsin',
     '        if fazla > 0 and float(yil) + fazla > azami + 1e-9:',
     '        if float(yil) + fazla > azami + 1e-9:',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', K, 'yillik: normal sinir sabit 45 olsun',
     '    normal = _p(next((k for k in (girdi.get("kurallar") or [])\n                      if k.get("kod") == "HAFTALIK_AZAMI"), {}),\n                "azami_saat", 45)\n    toplam = {}',
     '    normal = 45\n    toplam = {}',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', K, 'yillik: parametre okunmasin',
     '    azami = _p(tanim, "azami_saat_yil", 270)',
     '    azami = 270',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', D, 'yillik: bilinmeyen toplam bildirilmesin',
     '            if c.get("yil_ici_fazla_mesai_saat") is None:\n                hafta_net = sum(zaman.net_saat(a) for a in liste)',
     '            if False:\n                hafta_net = sum(zaman.net_saat(a) for a in liste)',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', D, 'yillik: fazla mesai yokken de bildirilsin',
     '                if hafta_net > normal + 1e-9:',
     '                if True:',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', M, 'yillik cozucu: kalan pay kirpilmasin',
     '                if kalan < fm_pay:\n                    fm_pay = kalan',
     '                if False:\n                    fm_pay = kalan',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', M, 'yillik cozucu: not yazilmasin',
     '                    self.notlar.append(\n                        "%s: yil ici fazla mesai %.1f saat, yillik tavana %.1f "',
     '                    (\n                        "%s: yil ici fazla mesai %.1f saat, yillik tavana %.1f "',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', K, 'GECE_YARISI_ASAN govdesi kaldirilsin',
     '@kural("GECE_YARISI_ASAN")\ndef gece_yarisi_asan(girdi, atamalar, tanim):',
     'def gece_yarisi_asan(girdi, atamalar, tanim):',
     'testler/test_yillik_fazla_mesai.py'),
    # ---- CALISMA_SAATLERI / K-52 (1 Ekim) -- iki taraf
    ('calisma', K, 'K-52 dogrulayici: pencere bitisi kontrol edilmesin',
     "                and pencere[\"bas\"] - 1e-9 <= bas and bit <= pencere[\"bit\"] + 1e-9:\n            return True\n    return False\n\n\n@kural(\"CALISMA_SAATLERI\")",
     "                and pencere[\"bas\"] - 1e-9 <= bas:\n            return True\n    return False\n\n\n@kural(\"CALISMA_SAATLERI\")",
     'testler/test_calisma_saatleri.py'),
    ('calisma', K, 'K-52 dogrulayici: gun suzgeci yok sayilsin',
     "        if gun % 7 in (pencere.get(\"gunler\") or range(7)) \\\n                and pencere[\"bas\"] - 1e-9 <= bas and bit <= pencere[\"bit\"] + 1e-9:\n            return True\n    return False\n\n\n@kural(\"CALISMA_SAATLERI\")",
     "        if pencere[\"bas\"] - 1e-9 <= bas and bit <= pencere[\"bit\"] + 1e-9:\n            return True\n    return False\n\n\n@kural(\"CALISMA_SAATLERI\")",
     'testler/test_calisma_saatleri.py'),
    ('calisma', K, 'K-52 dogrulayici: tanimsiz departman ihlal yazsin',
     '        if acik is None or acik:\n            continue',
     '        if acik:\n            continue',
     'testler/test_calisma_saatleri.py'),
    ('calisma', D, 'K-52: tanimsiz departman eksik_boyutlar yazmasin',
     '                if ekip not in saatler or saatler[ekip] is None:\n                    eksik.append({',
     '                if False:\n                    eksik.append({',
     'testler/test_calisma_saatleri.py'),
    ('calisma', M, 'K-52 cozucu: kapali sablon kapatilmasin',
     '        for (e, d, tid), v in self.x.items():\n            if (tid, d) in kapali:\n                self.m.Add(v == 0)',
     '        for (e, d, tid), v in self.x.items():\n            if False:\n                self.m.Add(v == 0)',
     'testler/test_calisma_saatleri.py'),
    ('calisma', M, 'K-52 cozucu: kural pasifken de kapatsin',
     '        if not self._calisma_saatleri_aktif:\n            return False\n        ekip = t.get("ekip")',
     '        ekip = t.get("ekip")',
     'testler/test_calisma_saatleri.py'),
    ('calisma', M, 'K-52 cozucu: pencere bitisi kontrol edilmesin',
     "                and pencere[\"bas\"] - 1e-9 <= bas and bit <= pencere[\"bit\"] + 1e-9:\n            return True\n    return False\n",
     "                and pencere[\"bas\"] - 1e-9 <= bas:\n            return True\n    return False\n",
     'testler/test_calisma_saatleri.py'),
    ('calisma', TS, 'K-52 on kontrol: kapali sablonu ulasiyor saysin',
     '                if kuruldu._departman_kapali_mi(sablon, d):     # K-52\n                    continue\n',
     '',
     'testler/test_calisma_saatleri.py'),
    # ---- HEDEF_ASIMI / K-53 (1 Ekim)
    ('hedef_asimi', M, 'K-53: ceza yazilmasin',
     '            if asim_kural and t.get("hedef") is not None:\n                asim = self.m.NewIntVar(0, kisi_sayisi, "ha_%d_%d" % (gun, saat))',
     '            if False:\n                asim = self.m.NewIntVar(0, kisi_sayisi, "ha_%d_%d" % (gun, saat))',
     'testler/test_hedef_asimi.py'),
    ('hedef_asimi', M, 'K-53: asim hedefin altini da cezalandirsin (mutlak)',
     '                self.m.Add(asim >= sum(atanmis) - t["hedef"])',
     '                self.m.Add(asim >= t["hedef"] - sum(atanmis))',
     'testler/test_hedef_asimi.py'),
    ('hedef_asimi', M, 'K-53: KAPSAMA profilinde agirlik DENGELI ile ayni',
     '    "HEDEF_ASIMI":           {"DENGELI": 3, "KAPSAMA": 1,  "CALISAN": 4},',
     '    "HEDEF_ASIMI":           {"DENGELI": 3, "KAPSAMA": 3,  "CALISAN": 4},',
     'testler/test_hedef_asimi.py'),
    ('hedef_asimi', K, 'K-53 dogrulayici: esitlik de ihlal',
     '        if sayi > hedef:\n            cikan.append(_ihlal("HEDEF_ASIMI"',
     '        if sayi >= hedef:\n            cikan.append(_ihlal("HEDEF_ASIMI"',
     'testler/test_hedef_asimi.py'),
]


def main():
    suzgec = sys.argv[1] if len(sys.argv) > 1 else None
    secilen = [m for m in MUTASYONLAR if suzgec is None or suzgec in m[0]]
    testler = sorted({m[5] for m in secilen})

    print("OZGUN KOD (baslangic):")
    for t in testler:
        rc, son = _kostur(t)
        print("  %-42s %s" % (t, son))
        if rc:
            print("\n⚠ OZGUN KOD KIRMIZI -- mutasyon sonuclari anlamsiz olur. DURDU.")
            sys.exit(2)

    yasayan = atlanan = 0
    print("\nMUTASYONLAR:")
    for grup, dosya, ad, eski, yeni, test in secilen:
        yol = os.path.join(BURASI, dosya)
        orijinal = io.open(yol, encoding="utf-8").read()
        once = _md5(yol)
        if orijinal.count(eski) != 1:
            print("  [%-10s] %-46s ATLANDI (capa %d kez)"
                  % (grup, ad, orijinal.count(eski)))
            atlanan += 1
            continue
        try:
            io.open(yol, "w", encoding="utf-8", newline="").write(
                orijinal.replace(eski, yeni))
            rc, son = _kostur(test)
        finally:
            io.open(yol, "w", encoding="utf-8", newline="").write(orijinal)
        assert _md5(yol) == once, "%s geri yazilamadi!" % dosya
        durum = "OLDU" if rc else "*** YASADI ***"
        if not rc:
            yasayan += 1
        print("  [%-10s] %-46s %-14s %s" % (grup, ad, durum, son))

    print("\nOZGUN KOD (bitis):")
    for t in testler:
        rc, son = _kostur(t)
        print("  %-42s %s" % (t, son))
        if rc:
            print("\n⚠ OZGUN KOD SONDA KIRMIZI -- bir dosya geri yazilamamis olabilir.")
            sys.exit(2)
    _onbellegi_sil()

    print("\nOZET: %d mutasyon · yasayan %d · atlanan %d"
          % (len(secilen), yasayan, atlanan))
    sys.exit(1 if (yasayan or atlanan) else 0)


if __name__ == "__main__":
    main()
