# -*- coding: utf-8 -*-
"""
MUTASYON KOSTURUCU -- elle secilmis bozmalar, TEKRARLANABILIR bicimde

NEDEN VAR (30 Eylul)
  Bu oturumda her yeni kural icin bozmalar elle, satir ici bir betikle
  denendi. O yontemin sessiz bir acigi CIKTI:

    Python derlenmis bytecode'u (__pycache__) gecerli sayarken kaynagin
    DEGISIKLIK ZAMANINA (saniye) ve BOYUTUNA bakar. Bir mutasyon AYNI
    UZUNLUKTA bir degisiklikse (`plan_geceler` -> `plan_gunleri`, ikisi de
    12 harf) ve dosya AYNI SANIYEDE geri yazilirsa, mutasyonlu bytecode
    ozgun kaynak icin de gecerli sayilir.

  Olculdu: `_gecmis_eksik` diskte dogruydu ama Python on ikinci
  mutasyonun bytecode'unu calistiriyordu; dogru bir test kirmizi yandi.
  Ters yon de mumkun: bir mutasyon bir oncekinin bytecode'uyla kosup
  sahte "oldu" ya da sahte "yasadi" verebilir.

BU BETIK NE YAPAR
  * her kosudan once __pycache__ silinir ve bytecode HIC yazilmaz
    (PYTHONDONTWRITEBYTECODE=1)
  * ozgun kod BASTA ve SONDA kosulur; ikisi de yesil olmak ZORUNDA --
    yoksa mutasyon sonuclari anlamsizdir ve betik durur
  * her mutasyondan sonra dosya geri yazilir ve md5 ile dogrulanir
  * capa bulunamazsa ATLANDI yazar -- sessizce gecmez

KOSTURMA
  cd C:\\Users\\PC\\Desktop\\Tshift\\09-motor
  py mutasyon_kostur.py            -> hepsi
  py mutasyon_kostur.py gecmis     -> adinda "gecmis" gecen gruplar
"""

import hashlib
import io
import os
import shutil
import subprocess
import sys

BURASI = os.path.dirname(os.path.abspath(__file__))
KOK = os.path.dirname(BURASI)


def _md5(yol):
    return hashlib.md5(io.open(yol, "rb").read()).hexdigest()


def _onbellegi_sil():
    for kok in (BURASI, os.path.join(KOK, "08-motor-testleri")):
        for dizin, alt, _ in os.walk(kok):
            for a in list(alt):
                if a in ("__pycache__", ".pytest_cache"):
                    shutil.rmtree(os.path.join(dizin, a), ignore_errors=True)
                    alt.remove(a)


def _kostur(test):
    _onbellegi_sil()
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
    p = subprocess.run([sys.executable, "-m", "pytest", test, "-q",
                        "--no-header", "-p", "no:cacheprovider"],
                       cwd=BURASI, env=env, capture_output=True, text=True)
    satirlar = [s for s in p.stdout.strip().splitlines() if s.strip()]
    return p.returncode, (satirlar[-1] if satirlar else p.stderr[-200:])


# (grup, dosya, ad, eski, yeni, test)
# ⚠ 1 Ekim (K-54): model.py'de her `self.m.Add(` `self._kisit(` oldu (donmus
#   gun suzgeci). Capalar da oyle guncellendi; yeni mutasyon yazarken
#   `self._kisit(` kullan, `self.m.Add(` capa bulamaz ve ATLANDI yazar.
K = "dogrulayici/kurallar.py"
D = "dogrulayici/denetle.py"
M = "cozucu/model.py"
C = "cozucu/coz.py"
TS = "cozucu/teshis.py"

MUTASYONLAR = [
    # ---- nitelik kapsamasi (30 Eylul) -- dogrulayici
    ("nitelik", K, "yalniz tam saate bak (ceyregi atla)",
     "    for t, g, an in _talep_anlari(girdi):\n        if ekip is not None and t.get(\"ekip\") != ekip:",
     "    for t, g, an in _talep_hucreleri(girdi):\n        if ekip is not None and t.get(\"ekip\") != ekip:",
     "testler/test_nitelik_kapsamasi.py"),
    ("nitelik", K, "saat listesini yok say",
     "    saat_kumesi = None if saatler is None else {int(s) for s in saatler}",
     "    saat_kumesi = None",
     "testler/test_nitelik_kapsamasi.py"),
    ("nitelik", K, "satirin yasal bayragini yok say",
     "                kod, tanim, ekip=ekip, gun=gun, saat=an, nitelik=aranan,",
     "                kod, tanim, ekip=ekip, gun=gun, saat=an, nitelik=aranan,\n                yasal=False, kabul_edilebilir=True,",
     "testler/test_nitelik_kapsamasi.py"),
    ("nitelik", K, "ekip kadrosu suzgecini yok say",
     "        if ekip is not None and ekip not in (c.get(\"ekipler\") or []):\n            continue",
     "        if False:\n            continue",
     "testler/test_nitelik_kapsamasi.py"),
    ("nitelik", K, "K-41 geri: molayi dus (sahada say)",
     "        varlik = sum(1 for a in ilgili if zaman.atanmis_mi(a, gun, an))",
     "        varlik = sum(1 for a in ilgili if zaman.sahada_mi(a, gun, an))",
     "testler/test_nitelik_kapsamasi.py"),
    # ---- nitelik kapsamasi -- cozucu (T-62)
    ("nitelik", M, "cozucu: saatler yoksa hic saat denetlenmesin",
     "                saat_kumesi = (None if saatler is None\n                               else {int(x) for x in saatler})",
     "                saat_kumesi = ({-1} if saatler is None\n                               else {int(x) for x in saatler})",
     "testler/test_nitelik_kapsamasi.py"),
    ("nitelik", M, "cozucu: nitelik tasiyan yoksa yine kisit yazilsin",
     "                if not uygun:\n                    self.notlar.append(\n                        \"%s: '%s' niteligini tasiyan uygun calisan yok, \"\n                        \"kisit yazilmadi\" % (kod, aranan))\n                    continue\n",
     "",
     "testler/test_nitelik_kapsamasi.py"),
    # ---- motorun kendi metrigi (T-65)
    ("metrik", C, "int() geri gelsin (kesirli siniri kirp)",
     "                   and a[\"gun\"] * 24 + a[\"bas\"] <= an\n                   < a[\"gun\"] * 24 + a[\"bit\"])",
     "                   and a[\"gun\"] * 24 + int(a[\"bas\"]) <= an\n                   < a[\"gun\"] * 24 + int(a[\"bit\"]))",
     "testler/test_motor_metrigi.py"),
    # ---- gece vardiyasi azami (K-26) -- dogrulayici
    ("gece_azami", K, "brut olc (molayi dusme)",
     "    return brut - mola\n", "    return brut\n",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "butun molalari dus (pencere disi dahil)",
     "    mola = sum(_kesisim(m0, m1, w0, w1)\n               for m0, m1 in zaman.mola_araliklari(atama))",
     "    mola = sum(m1 - m0 for m0, m1 in zaman.mola_araliklari(atama))",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "pencere gun sinirini asmasin (Z-5)",
     "        bit = zaman.mutlak(gun + (1 if pencere_bit <= pencere_bas else 0),\n                           pencere_bit)",
     "        bit = zaman.mutlak(gun, 24.0)",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "istisnayi hic uygulama",
     "            if istisnali_sektor and _gece_onayi_gecerli(c, girdi, gun):\n                continue",
     "            if False:\n                continue",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "yalniz sektore bak",
     "            if istisnali_sektor and _gece_onayi_gecerli(c, girdi, gun):",
     "            if istisnali_sektor:",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "yalniz onaya bak",
     "            if istisnali_sektor and _gece_onayi_gecerli(c, girdi, gun):",
     "            if _gece_onayi_gecerli(c, girdi, gun):",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "sinirda esitlik ihlal (>=)",
     "            if gece > azami + 1e-9:", "            if gece >= azami:",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", K, "suresi gecmis onay gecerli",
     "        return date.fromisoformat(bitis) >= gece", "        return True",
     "testler/test_gece_vardiyasi_azami.py"),
    # ---- gece vardiyasi azami -- cozucu
    ("gece_azami", M, "cozucu: kisit yazilmasin",
     "                    if (c[\"id\"], d, t[\"id\"]) in self.x:\n                        self._kisit(self.x[(c[\"id\"], d, t[\"id\"])] == 0)\n\n    def _izin(self):",
     "                    pass\n\n    def _izin(self):",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", M, "cozucu: istisna hic uygulanmasin",
     "                if istisnali and _gece_onayi_var(c, self.girdi, d):\n                    continue",
     "                if False:\n                    continue",
     "testler/test_gece_vardiyasi_azami.py"),
    ("gece_azami", M, "cozucu: yalniz onaya bak",
     "                if istisnali and _gece_onayi_var(c, self.girdi, d):",
     "                if _gece_onayi_var(c, self.girdi, d):",
     "testler/test_gece_vardiyasi_azami.py"),
    # ---- firma sinirlari -- dogrulayici
    ("firma", K, "asgari sure: net olc",
     "        bas, bit = zaman.aralik(a)\n        sure = bit - bas\n        if sure < asgari - 1e-9:",
     "        sure = zaman.net_saat(a)\n        if sure < asgari - 1e-9:",
     "testler/test_firma_sinirlari.py"),
    ("firma", K, "asgari sure: esitlik ihlal (<=)",
     "        if sure < asgari - 1e-9:", "        if sure <= asgari:",
     "testler/test_firma_sinirlari.py"),
    ("firma", K, "ardisik gece: calisma gunu say",
     "        geceler = {a[\"gun\"] for a in liste\n                   if _atama_gece_mi(girdi, a, sablonlar)}",
     "        geceler = {a[\"gun\"] for a in liste}",
     "testler/test_firma_sinirlari.py"),
    ("firma", M, "cozucu: gece kisiti yok",
     "                if terim:\n                    self._kisit(sum(terim) <= azami)",
     "                pass",
     "testler/test_firma_sinirlari.py"),
    ("firma", M, "cozucu: kisa sablon serbest",
     "                    if (c[\"id\"], d, t[\"id\"]) in self.x:\n                        self._kisit(self.x[(c[\"id\"], d, t[\"id\"])] == 0)\n\n    # ---- kapsama",
     "                    pass\n\n    # ---- kapsama",
     "testler/test_firma_sinirlari.py"),
    # ---- gecmis veri (T-28, K-42) -- dogrulayici
    ("gecmis", K, "gecmis listeye eklenmesin",
     "        liste.extend(_gecmis_kayitlari(girdi, kimlik))", "        pass",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "dinlenme: gecmis-gecmis cifti atlanmasin",
     "            if sonraki.get(\"_gecmis\"):\n                continue                      # gecmis kendi icinde",
     "            if False:\n                continue",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "cakisma: karisik cift de atlansin",
     "                if liste[i].get(\"_gecmis\") and liste[j].get(\"_gecmis\"):\n                    continue\n                ort",
     "                if liste[i].get(\"_gecmis\") or liste[j].get(\"_gecmis\"):\n                    continue\n                ort",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "tatil: gecmisteki pencere atlanmasin",
     "            if bas + pencere - 1 < 0:\n                continue                      # tamamen gecmiste",
     "            if False:\n                continue",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "seri: gecmisteki seri de sayilsin",
     "            if seri and g - 1 >= 0 and seri > en_uzun:",
     "            if seri and seri > en_uzun:",
     "testler/test_gecmis_veri.py"),
    # ⚠ 3 Ekim: bu capa K-56 ile iki yerde gecer oldu (devir_atamalari ayni
    #   satiri tasiyor) ve ATLANDI yaziyordu; baglamla tekillestirildi, K-56
    #   okuyucusuna ayri mutasyon kondu.
    ("gecmis", K, "gun>=0 kaydi da gecmis sayilsin",
     "        if gun is None or bas is None or bit is None or gun >= 0:\n            continue\n        a = {\"calisan\": kimlik,",
     "        if gun is None or bas is None or bit is None:\n            continue\n        a = {\"calisan\": kimlik,",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "K-56 okuyucusu: gun>=0 kaydi da devreden kapsama sayilsin",
     "                if gun is None or bas is None or bit is None or gun >= 0:\n                    continue\n                mbas, mbit",
     "                if gun is None or bas is None or bit is None:\n                    continue\n                mbas, mbit",
     "testler/test_gecmis_veri.py"),
    ("gecmis", K, "bilinen gunler listesi yok sayilsin",
     "    return ({g for g in (c.get(\"gecmis_bilinen_gunler\") or []) if g < 0}\n            | {k[\"gun\"] for k in kayitlar})",
     "    return {k[\"gun\"] for k in kayitlar}",
     "testler/test_gecmis_veri.py"),
    ("gecmis", D, "geri yuruyus bilinen bos gunde durmasin",
     "        elif d in bilinen:\n            return \"guvenli\", None",
     "        elif False:\n            return \"guvenli\", None",
     "testler/test_gecmis_veri.py"),
    ("gecmis", D, "kanitli ihlal de raporlansin",
     "            if k + plan_serisi >= esik:\n                return \"ihlal\", None",
     "            if k + plan_serisi >= esik:\n                return \"belirsiz\", d",
     "testler/test_gecmis_veri.py"),
    ("gecmis", D, "pazartesi bossa da raporlansin",
     "        if (\"VARDIYA_ARASI_DINLENME\" in aktif and 0 in plan_gunleri\n                and -1 not in bilinen):",
     "        if (\"VARDIYA_ARASI_DINLENME\" in aktif\n                and -1 not in bilinen):",
     "testler/test_gecmis_veri.py"),
    ("gecmis", D, "gece raporu pazartesi gece degilse de",
     "                                    _plan_serisi(plan_geceler), esik)",
     "                                    _plan_serisi(plan_gunleri), esik)",
     "testler/test_gecmis_veri.py"),
    # ---- gecmis veri -- cozucu
    ("gecmis", M, "cozucu: pazartesi dinlenme siniri yazilmasin",
     "                        if (d * 24 + t[\"bas\"] - bitis < asgari\n                                and (c[\"id\"], d, t[\"id\"]) in self.x):\n                            self._kisit(self.x[(c[\"id\"], d, t[\"id\"])] == 0)",
     "                        pass",
     "testler/test_gecmis_veri.py"),
    ("gecmis", M, "cozucu: ardisik gun gecmis penceresi yazilmasin",
     "                plan = range(0, min(HAFTA_GUN, bas + azami + 1))\n                self._kisit(sabit + sum(self._calisiyor(c[\"id\"], d)\n                                       for d in plan) <= azami)",
     "                pass",
     "testler/test_gecmis_veri.py"),
    ("gecmis", M, "cozucu: ardisik gece gecmis penceresi yazilmasin",
     "                if terim:\n                    self._kisit(sabit + sum(terim) <= azami)",
     "                pass",
     "testler/test_gecmis_veri.py"),
    ("gecmis", M, "cozucu: gecmisi HIC okumasin",
     "    cikan = []\n    for k in calisan.get(\"gecmis_vardiyalar\") or []:",
     "    cikan = []\n    for k in []:",
     "testler/test_gecmis_veri.py"),
    ("gecmis", M, "cozucu: gun>=0 kaydi da gecmis sayilsin",
     "        if gun is None or bas is None or bit is None or gun >= 0:\n            continue\n        bas, bit = float(bas), float(bit)",
     "        if gun is None or bas is None or bit is None:\n            continue\n        bas, bit = float(bas), float(bit)",
     "testler/test_gecmis_veri.py"),
    # ---- gece tespiti: isaretsiz tahmin (T-69), adalet boyutu (T-71)
    ("gece_tespiti", K, 'adalet: sablon isaretine bakma',
     '        return lambda a: _atama_gece_mi(girdi, a, sablonlar)',
     '        return lambda a: _atama_gece_mi({}, a, {})',
     'testler/test_gece_tespiti.py'),
    ("gece_tespiti", K, 'adalet: girdi sayaca gecmesin',
     '        sayac = _boyut_sayaci(boyut, girdi)',
     '        sayac = _boyut_sayaci(boyut)',
     'testler/test_gece_tespiti.py'),
    # ---- sahte PDKS uretici (30 Eylul aksami) -- olcum aracinin kendisi
    ("pdks", '../08-motor-testleri/gercekci-veri-seti/sahte_pdks.py', 'yakalanan gerceklesende olmayan kayit icersin',
     '            k for k in yasanan if rnd.random() < ayar["kayit_orani"]]',
     '            k for k in yasanan if rnd.random() < ayar["kayit_orani"]] + [\n            {"gun": -1, "bas": 1, "bit": 2}]',
     '../08-motor-testleri/gercekci-veri-seti/testler/test_sahte_pdks.py'),
    ("pdks", '../08-motor-testleri/gercekci-veri-seti/sahte_pdks.py', 'bilinen gun = planli gun',
     '        bilinen[kimlik] = sorted({k["gun"] for k in yakalanan})',
     '        bilinen[kimlik] = sorted({a["gun"] - kaydir for a in kisiye.get(kimlik, [])})',
     '../08-motor-testleri/gercekci-veri-seti/testler/test_sahte_pdks.py'),
    ("pdks", '../08-motor-testleri/gercekci-veri-seti/sahte_pdks.py', 'uyum orani yok sayilsin',
     '            if r < ayar["uyum"]:',
     '            if r < 0.5:',
     '../08-motor-testleri/gercekci-veri-seti/testler/test_sahte_pdks.py'),
    ("pdks", '../08-motor-testleri/gercekci-veri-seti/sahte_pdks.py', 'kayda gece isareti eklensin',
     '            yasanan.append({"gun": a["gun"] - kaydir, "bas": bas, "bit": bit})',
     '            yasanan.append({"gun": a["gun"] - kaydir, "bas": bas, "bit": bit,\n                            "gece": False})',
     '../08-motor-testleri/gercekci-veri-seti/testler/test_sahte_pdks.py'),
    ("pdks", '../08-motor-testleri/gercekci-veri-seti/sahte_pdks.py', 'cakisma dinlenme satiriyla eslenmesin',
     'HABERCI = {"CAKISMA_YOK": "VARDIYA_ARASI_DINLENME"}',
     'HABERCI = {}',
     '../08-motor-testleri/gercekci-veri-seti/testler/test_sahte_pdks.py'),
    # ---- sure butcesi (T-59, 30 Eylul aksami)
    ("butce", C, 'birinci asama eski butcesini alsin',
     '        pay = _ilk_asama_payi(ayar)\n',
     '        pay = float(ayar.get("ilk_asama_saniye", 120))\n',
     'testler/test_sure_butcesi.py'),
    ("butce", C, 'ana cozum butcenin tamamini alsin',
     '    ana_butce = max(1.0, float(ayar["azami_saniye"]) - ilk_asama)',
     '    ana_butce = float(ayar["azami_saniye"])',
     'testler/test_sure_butcesi.py'),
    ("butce", C, 'ana cozume sifir kalabilsin',
     '    ana_butce = max(1.0, float(ayar["azami_saniye"]) - ilk_asama)',
     '    ana_butce = max(0.0, float(ayar["azami_saniye"]) - ilk_asama)',
     'testler/test_sure_butcesi.py'),
    ("butce", C, 'durma sebebi eski kiyasla',
     '    if butce is None:\n        butce = ayar["azami_saniye"]',
     '    butce = ayar["azami_saniye"]',
     'testler/test_sure_butcesi.py'),
    # ---- 30 Eylul gecesi: K-43 isaret tabani, K-44 yasal gece siniri,
    #      K-45 gece haftasi, K-46 hafta sonu, K-47 ozet, T-76 teshis
    ('isaret', K, 'K-43 geri: isaret her yonde ezsin (dogrulayici)',
     '        return (yasal or bool(sablon["gece_vardiyasi"])), False\n    return yasal, True',
     '        return bool(sablon["gece_vardiyasi"]), False\n    return yasal, True',
     'testler/test_gece_uygunlugu.py'),
    ('isaret', K, 'K-43 geri: isaret yok sayilsin (dogrulayici)',
     '        return (yasal or bool(sablon["gece_vardiyasi"])), False\n    return yasal, True',
     '        return yasal, False\n    return yasal, True',
     'testler/test_gece_tespiti.py'),
    ('isaret', K, 'K-43 geri: gecmis kaydin isareti ezsin',
     '        if "_gece" in a:\n            return yasal or bool(a["_gece"])\n        return yasal',
     '        if "_gece" in a:\n            return bool(a["_gece"])\n        return yasal',
     'testler/test_gecmis_veri.py'),
    ('isaret', M, 'K-43 geri: isaret her yonde ezsin (cozucu)',
     '        return (yasal or bool(sablon["gece_vardiyasi"])), False\n    return yasal, True',
     '        return bool(sablon["gece_vardiyasi"]), False\n    return yasal, True',
     'testler/test_gece_uygunlugu.py'),
    ('isaret', M, 'K-43 geri: cozucu gecmis kaydin isareti ezsin',
     '    return _yasal_gece_postasi(bas, bit) or bool(isaret)',
     '    return bool(isaret) if isaret is not None else _yasal_gece_postasi(bas, bit)',
     'testler/test_gecmis_veri.py'),
    ('isaret', M, 'ezilen isaret notu yazilmasin',
     '            elif gece and not t.get("gece_vardiyasi"):\n                ezilenler.append(t["id"])',
     '            elif False:\n                ezilenler.append(t["id"])',
     'testler/test_gece_uygunlugu.py'),
    ('gece_tespiti', K, 'tahmin: eski olcu (ayni gun, en ufak degme)',
     '    yasal = _yasal_gece_postasi_mi(\n        {"gun": 0, "bas": sablon["bas"], "bit": sablon["bit"]})',
     '    yasal = (min(float(sablon["bit"]), 30.0) - max(float(sablon["bas"]), 20.0) > 0)',
     'testler/test_gece_tespiti.py'),
    ('gece_tespiti', M, 'cozucu tahmin: eski olcu (ayni gun, en ufak degme)',
     '    yasal = _yasal_gece_postasi(sablon["bas"], sablon["bit"])\n    if "gece_vardiyasi" in sablon:',
     '    yasal = (min(float(sablon["bit"]), 30.0) - max(float(sablon["bas"]), 20.0) > 0)\n    if "gece_vardiyasi" in sablon:',
     'testler/test_gece_tespiti.py'),
    ('gece_azami', K, 'K-44 geri: posta olcusu yazilmasin',
     '            net = zaman.net_saat(a)\n            if net > azami + 1e-9:',
     '            net = zaman.net_saat(a)\n            if False:',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'K-44: posta olcusu brut olsun',
     '            net = zaman.net_saat(a)\n            if net > azami + 1e-9:',
     '            net = zaman.brut_saat(a)\n            if net > azami + 1e-9:',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'K-44: istisna posta olcusunde uygulanmasin',
     '            if istisnali_sektor and _gece_onayi_gecerli(c, girdi, a["gun"]):\n                continue\n            net',
     '            if False:\n                continue\n            net',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'K-44: ayni vardiya iki kez yazilsin (V-1 yok)',
     '            if any(_kesisim(b0, b1, w0, w1) > 0 for b0, b1 in yazilan):\n                continue',
     '            if False:\n                continue',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'yasal gece: yarisi da gece sayilsin',
     '    return 2 * gece > (bit - bas) + 1e-9\n\n\n# Yonetmelik md. 8/3',
     '    return 2 * gece >= (bit - bas) - 1e-9\n\n\n# Yonetmelik md. 8/3',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'yasal gece: en ufak ortusme yeter',
     '    return 2 * gece > (bit - bas) + 1e-9\n\n\n# Yonetmelik md. 8/3',
     '    return gece > 0\n\n\n# Yonetmelik md. 8/3',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', K, 'yasal gece: onceki gecenin donemine bakma',
     '    for d in (gun - 1, gun, gun + 1):\n        w0 = zaman.mutlak(d, p_bas)',
     '    for d in (gun, gun + 1):\n        w0 = zaman.mutlak(d, p_bas)',
     'testler/test_gece_tespiti.py'),
    ('gece_azami', M, 'cozucu K-44 geri: posta suzgeci yazilmasin',
     '        asanlar = asanlar + [(t, _net_saat(t)) for t in yasal_asanlar]',
     '        asanlar = asanlar + []',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', M, 'cozucu K-44: brut olcsun',
     '                         and _net_saat(t) > azami + 1e-9\n',
     '                         and (float(t["bit"]) - float(t["bas"])) > azami + 1e-9\n',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', M, 'cozucu yasal gece: en ufak ortusme yeter',
     '    return 2 * gece > (bit - bas) + 1e-9\n\n\ndef _net_saat(sablon):',
     '    return gece > 0\n\n\ndef _net_saat(sablon):',
     'testler/test_hafta_kurallari.py'),
    ('gece_azami', M, 'cozucu yasal gece: yarisi da gece sayilsin',
     '    return 2 * gece > (bit - bas) + 1e-9\n\n\ndef _net_saat(sablon):',
     '    return 2 * gece >= (bit - bas) - 1e-9\n\n\ndef _net_saat(sablon):',
     'testler/test_gece_vardiyasi_azami.py'),
    ('gece_azami', M, 'cozucu yasal gece: onceki gece yok',
     '    for w0 in (-4.0, 20.0, 44.0):',
     '    for w0 in (20.0, 44.0):',
     'testler/test_gece_tespiti.py'),
    ('hafta', K, 'hafta: sifira dogru yuvarla (int)',
     'def _hafta(gun):\n    return gun // 7',
     'def _hafta(gun):\n    return int(gun / 7)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'gece haftasi: yarisi da yeter (>=)',
     '    return 2 * gece_saat > toplam + 1e-9',
     '    return 2 * gece_saat >= toplam - 1e-9',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'gece haftasi: vardiya sayisiyla olc',
     '    gece_saat = sum(zaman.brut_saat(a) for a in gece)\n    toplam = sum(zaman.brut_saat(a) for a in hafta_listesi)',
     '    gece_saat = len(gece)\n    toplam = len(hafta_listesi)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'gece haftasi: asgari_gece yok sayilsin',
     '    if asgari_gece is not None and len(gece) >= int(asgari_gece) > 0:\n        return True\n    gece_saat',
     '    if False:\n        return True\n    gece_saat',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'gecmis hafta: yarim bilinen hafta da degerlendirilsin',
     '            if h < 0 and _hafta_tam_bilinen_mi(h, bilinen)\n            and _gece_haftasi_mi(hl, asgari_gece)}',
     '            if h < 0\n            and _gece_haftasi_mi(hl, asgari_gece)}',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'devri: pencere kesintisiz seri olsun (G-G-D-G serbest)',
     '            sayi = sum(1 for h in range(hafta - pencere + 1, hafta + 1)\n                       if h in gece_haftalari)',
     '            sayi = _geriye_seri(gece_haftalari, hafta)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'devri: sinirda esitlik ihlal (>=)',
     '            if sayi > azami:\n                geceler = [a for a in haftalar[hafta]',
     '            if sayi >= azami:\n                geceler = [a for a in haftalar[hafta]',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'devri: ust sinir kirpilmasin',
     '    return max(1, min(verilen, GECE_HAFTASI_YASAL_UST_SINIR)), verilen',
     '    return max(1, verilen), verilen',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'devri: gecmis okunmasin',
     '    for kimlik, liste in sorted(_kisiye_gore_gecmisli(girdi, atamalar).items()):\n        haftalar = _haftaya_gore(liste)',
     '    for kimlik, liste in sorted(_kisiye_gore(atamalar).items()):\n        haftalar = _haftaya_gore(liste)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'devri: K-40 isaretine bak (firma tanimi)',
     '    gece = [a for a in hafta_listesi if _yasal_gece_postasi_mi(a)]',
     '    gece = [a for a in hafta_listesi if _atama_gece_mi({}, a, {})]',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'cogunluk gunu: baslangic gunu olsun',
     '    return a["gun"] + 1 if 2 * tasan > (bit - bas) + 1e-9 else a["gun"]',
     '    return a["gun"]',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'cogunluk gunu: en ufak tasma ertesi gun',
     '    return a["gun"] + 1 if 2 * tasan > (bit - bas) + 1e-9 else a["gun"]',
     '    return a["gun"] + 1 if tasan > 0 else a["gun"]',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'hsonu: tek gun yeter',
     '        tam = {h for h, g in gunler.items() if g >= {5, 6}}',
     '        tam = {h for h, g in gunler.items() if g}',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'hsonu: sinirda esitlik ihlal (>=)',
     '            if seri > azami:\n                ilk = min(_cogunluk_gunu(a) for a in liste',
     '            if seri >= azami:\n                ilk = min(_cogunluk_gunu(a) for a in liste',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'hsonu: gecmis okunmasin',
     '    for kimlik, liste in sorted(_kisiye_gore_gecmisli(girdi, atamalar).items()):\n        gunler = _calisilan_hafta_sonu_gunleri(liste)',
     '    for kimlik, liste in sorted(_kisiye_gore(atamalar).items()):\n        gunler = _calisilan_hafta_sonu_gunleri(liste)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', K, 'adalet hafta sonu: baslangic gunuyle',
     '        return lambda a: _hafta_sonu_gunu(a) is not None',
     '        return lambda a: a["gun"] in (5, 6)',
     'testler/test_gece_tespiti.py'),
    ('hafta', D, 'rapor devri: kanitli ihlal de raporlansin',
     '                if (len(kanitli) < azami\n                        and len(kanitli) + len(bilinmeyen) >= azami):',
     '                if len(kanitli) + len(bilinmeyen) >= azami:',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'rapor devri: bilinmeyen yetmese de raporlansin',
     '                if (len(kanitli) < azami\n                        and len(kanitli) + len(bilinmeyen) >= azami):',
     '                if len(kanitli) < azami and bilinmeyen:',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'rapor devri: bu hafta gece haftasi degilken de',
     '            if kurallar._gece_haftasi_mi(haftalar.get(0, []), asgari_gece):\n                azami, _ = kurallar._gece_haftasi_azami(tanim)',
     '            if True:\n                azami, _ = kurallar._gece_haftasi_azami(tanim)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'rapor hsonu: bilinen bos hafta sonunda durmasin',
     '                    if 7 * h + 5 in bilinen and 7 * h + 6 in bilinen:\n                        break                   # bilinen, tam calisilmamis',
     '                    if False:\n                        break',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'rapor hsonu: kanitli olan da raporlansin',
     '                    if gunler.get(h, set()) >= {5, 6}:\n                        continue                # kanitli',
     '                    if False:\n                        continue',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'rapor hsonu: plan tek gunken de',
     '            if gunler.get(0, set()) >= {5, 6}:\n                azami = int(kurallar._p(aktif["ARDISIK_HAFTA_SONU_LIMIT"],',
     '            if gunler.get(0, set()):\n                azami = int(kurallar._p(aktif["ARDISIK_HAFTA_SONU_LIMIT"],',
     'testler/test_hafta_kurallari.py'),
    ('hafta', D, 'ust sinir raporu yazilmasin',
     '            if verilen != azami:\n                eksik.append({',
     '            if False:\n                eksik.append({',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: kisit yazilmasin',
     '            if gece_terim:\n                self._kisit(2 * sum(gece_terim) <= sum(toplam_terim))',
     '            if False:\n                self._kisit(2 * sum(gece_terim) <= sum(toplam_terim))',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: esitlik de yasak (<)',
     '                self._kisit(2 * sum(gece_terim) <= sum(toplam_terim))',
     '                self._kisit(2 * sum(gece_terim) < sum(toplam_terim))',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: asgari_gece kisiti yazilmasin',
     '                if asgari_gece is not None and int(asgari_gece) > 0:\n                    self._kisit(sum(gece_sayi) <= int(asgari_gece) - 1)',
     '                pass',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: kanitli sayisi esikten dusukken de',
     '            if kanitli < azami:\n                continue\n            gece_terim',
     '            if kanitli < 0:\n                continue\n            gece_terim',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: ust sinir kirpilmasin',
     '        azami = max(1, min(verilen, 2))',
     '        azami = max(1, verilen)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: yarim bilinen hafta degerlendirilsin',
     '        if not all(d in bilinen for d in range(7 * hafta, 7 * hafta + 7)):\n            return False',
     '        if False:\n            return False',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: gecmis gece haftasi vardiya sayisiyla',
     '        gece_saat = sum(b1 - b0 for b0, b1 in gece)\n        toplam = sum(b1 - b0 for _, b0, b1 in kayitlar)',
     '        gece_saat = len(gece)\n        toplam = len(kayitlar)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: gecmiste yarisi da yeter',
     '        return 2 * gece_saat > toplam + 1e-9',
     '        return 2 * gece_saat >= toplam - 1e-9',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: hafta sifira yuvarlansin',
     '                    if g // 7 == hafta]',
     '                    if int(g / 7) == hafta]',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu devri: pencere yerine yalniz gecen hafta',
     '            kanitli = sum(1 for h in range(-(2 * azami - 1), 0)',
     '            kanitli = sum(1 for h in range(-1, 0)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu hsonu: kisit yazilmasin',
     '            for x1 in cumartesi:\n                for x2 in pazar:\n                    self._kisit(x1 + x2 <= 1)',
     '            pass',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu hsonu: tek gun yeter (gecmis)',
     '        return gunler >= {5, 6}',
     '        return bool(gunler)',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu hsonu: bir hafta yetsin',
     '            if not all(self._hafta_sonu_gecmiste_tam(c, h)\n                       for h in range(-1, -azami - 1, -1)):',
     '            if not all(self._hafta_sonu_gecmiste_tam(c, h)\n                       for h in range(-1, -2, -1)):',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cogunluk kaymasi: hep baslangic gunu',
     '    return 1 if 2 * tasan > (bit - bas) + 1e-9 else 0',
     '    return 0',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cogunluk kaymasi: en ufak tasma',
     '    return 1 if 2 * tasan > (bit - bas) + 1e-9 else 0',
     '    return 1 if tasan > 0 else 0',
     'testler/test_hafta_kurallari.py'),
    ('hafta', M, 'cozucu adalet hafta sonu: baslangic gunuyle',
     '            return lambda t, d: _hafta_sonu_gunu(d, t["bas"], t["bit"]) is not None',
     '            return lambda t, d: d in (5, 6)',
     'testler/test_hafta_kurallari.py'),
    ('rapor', D, 'ozet: yasal bayragi okunmasin',
     '        if yasal.get(x["kural"]):\n            k["yasal"] = True',
     '        pass',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    ('rapor', D, 'ozet: siralama yasal one almasin',
     '    liste.sort(key=lambda k: (not k["yasal"], k["calisan"]))',
     '    liste.sort(key=lambda k: k["calisan"])',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    ('rapor', D, 'ozet: kisi sayisi satir sayisi olsun',
     '        "kisi": len(liste),',
     '        "kisi": len(gecmis_eksik),',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    ('teshis', TS, "T-76 geri: sure asimi 'engellemiyor' sayilsin",
     '        elif durum is None:\n            belirsiz.append(dict(satir, deneme_saniye=saniye))',
     '        elif False:\n            belirsiz.append(dict(satir, deneme_saniye=saniye))',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    ('teshis', TS, 'T-76: kural basina butce sabit 10',
     '    saniye = float((ayar or {}).get("teshis_kural_saniye", 10))',
     '    saniye = 10.0',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    ('teshis', TS, 'T-76: not yazilmasin',
     '    if not engelleyen and belirsiz:\n        cevap["teshis"]["not"] = (',
     '    if False:\n        cevap["teshis"]["not"] = (',
     'testler/test_rapor_ozeti_ve_teshis.py'),
    # ---- T-78 (1 Ekim): ceyrege sigmayan mola -- her degisiklik tek tek geri
    ('mola_t78', M, 'T-78 geri: pencere araligi round ile',
     '    sure_q = _ceyrek_yukari(sure)\n',
     '    sure_q = int(round(sure * CEYREK))\n',
     'testler/test_net_saat_uyumu.py'),
    ('mola_t78', M, 'T-78 geri: dilim kumesi bitisi round ile',
     '    return list(range(_q(gun, baslangic),\n                      _q(gun, baslangic) + _ceyrek_yukari(dk / 60.0)))',
     '    return list(range(_q(gun, baslangic), _q(gun, baslangic + dk / 60.0)))',
     'testler/test_net_saat_uyumu.py'),
    # Not: "yemek-dinlenme cakismasi ceyrek kumesiyle" mutasyonu ESDEGER
    # cikti ve listeye alinmadi: dilim kumesi yukari yuvarlandigi icin ceyrek
    # kesisimi ile gercek kesisim ayni cevabi veriyor (baslangiclar izgarada).
    ('mola_t78', M, 'T-78: yemek-dinlenme kisiti hic yazilmasin',
     '                    if _gercek_kesisiyor(s, sure, sy, yemek_sure):',
     '                    if False:',
     'testler/test_net_saat_uyumu.py'),
    ('mola_t78', M, 'T-78: emniyet kemeri kaldirilsin (pencere de round)',
     '            onceki = [(i, s) for s in adaylar]',
     '            onceki = []',
     'testler/test_net_saat_uyumu.py'),
    ('mola_t78', M, 'T-78: yukari yuvarlama asagi olsun',
     '    return int(math.ceil(saat * CEYREK - 1e-9))',
     '    return int(math.floor(saat * CEYREK + 1e-9))',
     'testler/test_net_saat_uyumu.py'),
    ('mola_t78', M, 'T-78: gercek kesisim ucu uca degeni de kesisim saysin',
     '    return bas1 < bas2 + sure2_sa - 1e-9 and bas2 < bas1 + sure1_sa - 1e-9',
     '    return bas1 <= bas2 + sure2_sa + 1e-9 and bas2 <= bas1 + sure1_sa + 1e-9',
     'testler/test_net_saat_uyumu.py'),
    # ---- T-60 (1 Ekim): birinci asama molalari sabitler, ipucu tam
    ('ilk_asama', C, 'T-60: molalar sabitlenmesin (eski birinci asama)',
     '    sabitlenen = _molalari_sabitle(kuruldu) if mola_sabit else []',
     '    sabitlenen = []',
     'testler/test_ilk_asama.py'),
    ('ilk_asama', C, 'T-60: alanlar geri acilmasin',
     '        _molalari_serbest_birak(kuruldu, sabitlenen)\n        amaci_geri_koy()',
     '        amaci_geri_koy()',
     'testler/test_ilk_asama.py'),
    ('ilk_asama', C, 'T-60: ipucu yalniz x icin yazilsin (eski yarim ipucu)',
     '    proto.solution_hint.vars.extend(list(range(len(degerler))))\n    proto.solution_hint.values.extend(degerler)',
     '    proto.solution_hint.vars.extend([v.Index() for v in kuruldu.x.values()])\n    proto.solution_hint.values.extend([degerler[v.Index()] for v in kuruldu.x.values()])',
     'testler/test_ilk_asama.py'),
    ('ilk_asama', M, 'T-60: sabit secim yemekle cakismaya bakmasin',
     "                     if not (sy is not None and _gercek_kesisiyor(s_, sure, sy, ysure))\n",
     "                     if True\n",
     'testler/test_ilk_asama.py'),
    ('ilk_asama', M, 'T-60: sabit secim ideale degil ilk adaya gitsin',
     '            sec = min(uygun, key=lambda s_: (abs(s_ - ideal), s_))',
     '            sec = uygun[0]',
     'testler/test_ilk_asama.py'),
    ('ilk_asama', C, 'T-60: sabitleme yemegi atlasin',
     '        if sy is not None and s is not None and s != sy:\n            sabitlenen.append(v.Index())',
     '        if False:\n            sabitlenen.append(v.Index())',
     'testler/test_ilk_asama.py'),
    # ---- T-21 / K-50 (1 Ekim): cok ekipli calisan kime sayilir
    ('cok_ekipli', M, 'K-50: hepsi modu da tek gibi saysin',
     '        if self.cok_ekipli_sayim == "tek":\n            return self._atama_ekibi(c, t) == ekip\n        return ekip in (c.get("ekipler") or [])',
     '        return self._atama_ekibi(c, t) == ekip',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', M, 'K-50: tek modu da hepsi gibi saysin',
     '        if self.cok_ekipli_sayim == "tek":\n            return self._atama_ekibi(c, t) == ekip\n        return ekip in (c.get("ekipler") or [])',
     '        return ekip in (c.get("ekipler") or [])',
     'testler/test_cok_ekipli.py'),
    # ⚠ 3 Ekim: iki capa K-56 ile (`_devir_elle` kosulu) bozulmustu, ATLANDI
    #   yaziyordu; yeni metne cekildi.
    ('cok_ekipli', K, 'K-50 dogrulayici: tek modda da uyelige saysin',
     '    if mod != "hepsi" or atama.get("_devir_elle"):\n        return False',
     '    if atama.get("_devir_elle"):\n        return False',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', K, 'K-50 dogrulayici: hepsi modda da yalniz atamanin ekibi',
     '    if mod != "hepsi" or atama.get("_devir_elle"):\n        return False          # elle verilen devir sayisinin kisisi yok (K-56)\n    return ekip in uyelik.get(atama.get("calisan"), ())',
     '    return False',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', K, 'K-50 dogrulayici: nitelik kapsamasi atamanin ekibine baksin (eski)',
     '              and ekibe_sayilir(a, ekip, uyelik, mod)]',
     '              and (ekip is None or a.get("ekip") == ekip)]',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', D, 'K-50: baska ekipten kapsama sayilmasin',
     '        if sayi > kendi:\n            baska_hucre += 1',
     '        if False:\n            baska_hucre += 1',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', C, 'K-50: cikti ilk ekibi yazsin (eski)',
     '        ekip = kuruldu._atama_ekibi(kisi or {}, sablon)',
     '        ekip = (kisi or {}).get("ekipler", [None])[0]',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', TS, 'K-50: on kontrol baska ekibin sablonunu gormesin (eski)',
     '                if not hepsi or not any(',
     '                if True or not any(',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', TS, 'K-50: teshis mumkun sayisi ekip suzgecsiz (eski)',
     '            if not kuruldu._sayilir(c, t, ekip):\n                continue\n',
     '',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', M, 'K-50: nitelik toplaminda ekip suzgeci kalksin',
     '                           if (ekip is None or self._sayilir(c, t, ekip))\n                           and dilim in _dilimler(d, t["bas"], t["bit"])]',
     '                           if dilim in _dilimler(d, t["bas"], t["bit"])]',
     'testler/test_cok_ekipli.py'),
    ('cok_ekipli', M, 'K-50: tek modda ekipsiz sablon notu yazilmasin',
     '        if self.cok_ekipli_sayim == "tek":\n            for t in self.sablonlar:',
     '        if False:\n            for t in self.sablonlar:',
     'testler/test_cok_ekipli.py'),
    # ---- T-18 / K-49 (1 Ekim): "bakamadim" kapidan gecemez
    ('kapi', D, 'K-49: kapi denetlenemeyeni gormesin (eski)',
     '        "yayin_kapisi": yayin_kapisi(ihlaller, girdi, uygulanmayan, eksik_boyutlar),',
     '        "yayin_kapisi": yayin_kapisi(ihlaller),',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    ('kapi', D, 'K-49: yasal da kabul bekleyen olsun',
     '    elif yasal:\n        etki = "engelliyor"',
     '    elif False:\n        etki = "engelliyor"',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    ('kapi', D, 'K-49: gerekcesiz kabul de kabul sayilsin',
     '        if (k.get("gerekce") or "").strip():\n            kabuller[k.get("kod")] = k',
     '        kabuller[k.get("kod")] = k',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    ('kapi', D, 'K-49: yumusak da kabul beklesin',
     '    if not sert:\n        etki = "rapor"',
     '    if False:\n        etki = "rapor"',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    ('kapi', D, 'K-49: kirpma raporu da bakamadim sayilsin',
     '        if not e.get("denetlenemedi"):\n            continue',
     '        if False:\n            continue',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    ('kapi', D, 'K-49: kabul bekleyen denetlenemeyen yayini acik biraksin',
     '        "yayinlanabilir": not acik_sert and not d_engelleyen and not d_bekleyen,',
     '        "yayinlanabilir": not acik_sert and not d_engelleyen,',
     'testler/test_yayin_kapisi_denetlenemeyen.py'),
    # ---- YILLIK_FAZLA_MESAI_TAVANI (1 Ekim) -- iki taraf
    ('yillik', K, 'yillik: tavana esit de ihlal olsun (>=)',
     '        if fazla > 0 and float(yil) + fazla > azami + 1e-9:',
     '        if fazla > 0 and float(yil) + fazla >= azami - 1e-9:',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', K, 'yillik: fazla mesai yokken de yazsin',
     '        if fazla > 0 and float(yil) + fazla > azami + 1e-9:',
     '        if float(yil) + fazla > azami + 1e-9:',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', K, 'yillik: normal sinir sabit 45 olsun',
     '    normal = _p(next((k for k in (girdi.get("kurallar") or [])\n                      if k.get("kod") == "HAFTALIK_AZAMI"), {}),\n                "azami_saat", 45)\n    toplam = {}',
     '    normal = 45\n    toplam = {}',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', K, 'yillik: parametre okunmasin',
     '    azami = _p(tanim, "azami_saat_yil", 270)',
     '    azami = 270',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', D, 'yillik: bilinmeyen toplam bildirilmesin',
     '            if c.get("yil_ici_fazla_mesai_saat") is None:\n                hafta_net = sum(zaman.net_saat(a) for a in liste)',
     '            if False:\n                hafta_net = sum(zaman.net_saat(a) for a in liste)',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', D, 'yillik: fazla mesai yokken de bildirilsin',
     '                if hafta_net > normal + 1e-9:',
     '                if True:',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', M, 'yillik cozucu: kalan pay kirpilmasin',
     '                if kalan < fm_pay:\n                    fm_pay = kalan',
     '                if False:\n                    fm_pay = kalan',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', M, 'yillik cozucu: not yazilmasin',
     '                    self.notlar.append(\n                        "%s: yil ici fazla mesai %.1f saat, yillik tavana %.1f "',
     '                    (\n                        "%s: yil ici fazla mesai %.1f saat, yillik tavana %.1f "',
     'testler/test_yillik_fazla_mesai.py'),
    ('yillik', K, 'GECE_YARISI_ASAN govdesi kaldirilsin',
     '@kural("GECE_YARISI_ASAN")\ndef gece_yarisi_asan(girdi, atamalar, tanim):',
     'def gece_yarisi_asan(girdi, atamalar, tanim):',
     'testler/test_yillik_fazla_mesai.py'),
    # ---- CALISMA_SAATLERI / K-52 (1 Ekim) -- iki taraf
    ('calisma', K, 'K-52 dogrulayici: pencere bitisi kontrol edilmesin',
     "                and pencere[\"bas\"] - 1e-9 <= bas and bit <= pencere[\"bit\"] + 1e-9:\n            return True\n    return False\n\n\n@kural(\"CALISMA_SAATLERI\")",
     "                and pencere[\"bas\"] - 1e-9 <= bas:\n            return True\n    return False\n\n\n@kural(\"CALISMA_SAATLERI\")",
     'testler/test_calisma_saatleri.py'),
    ('calisma', K, 'K-52 dogrulayici: gun suzgeci yok sayilsin',
     "        if gun % 7 in (pencere.get(\"gunler\") or range(7)) \\\n                and pencere[\"bas\"] - 1e-9 <= bas and bit <= pencere[\"bit\"] + 1e-9:\n            return True\n    return False\n\n\n@kural(\"CALISMA_SAATLERI\")",
     "        if pencere[\"bas\"] - 1e-9 <= bas and bit <= pencere[\"bit\"] + 1e-9:\n            return True\n    return False\n\n\n@kural(\"CALISMA_SAATLERI\")",
     'testler/test_calisma_saatleri.py'),
    ('calisma', K, 'K-52 dogrulayici: tanimsiz departman ihlal yazsin',
     '        if acik is None or acik:\n            continue',
     '        if acik:\n            continue',
     'testler/test_calisma_saatleri.py'),
    ('calisma', D, 'K-52: tanimsiz departman eksik_boyutlar yazmasin',
     '                if ekip not in saatler or saatler[ekip] is None:\n                    eksik.append({',
     '                if False:\n                    eksik.append({',
     'testler/test_calisma_saatleri.py'),
    ('calisma', M, 'K-52 cozucu: kapali sablon kapatilmasin',
     '        for (e, d, tid), v in self.x.items():\n            if (tid, d) in kapali:\n                self._kisit(v == 0)',
     '        for (e, d, tid), v in self.x.items():\n            if False:\n                self._kisit(v == 0)',
     'testler/test_calisma_saatleri.py'),
    ('calisma', M, 'K-52 cozucu: kural pasifken de kapatsin',
     '        if not self._calisma_saatleri_aktif:\n            return False\n        ekip = t.get("ekip")',
     '        ekip = t.get("ekip")',
     'testler/test_calisma_saatleri.py'),
    ('calisma', M, 'K-52 cozucu: pencere bitisi kontrol edilmesin',
     "                and pencere[\"bas\"] - 1e-9 <= bas and bit <= pencere[\"bit\"] + 1e-9:\n            return True\n    return False\n",
     "                and pencere[\"bas\"] - 1e-9 <= bas:\n            return True\n    return False\n",
     'testler/test_calisma_saatleri.py'),
    ('calisma', TS, 'K-52 on kontrol: kapali sablonu ulasiyor saysin',
     '                if kuruldu._departman_kapali_mi(sablon, d):     # K-52\n                    continue\n',
     '',
     'testler/test_calisma_saatleri.py'),
    # ---- HEDEF_ASIMI / K-53 (1 Ekim)
    ('hedef_asimi', M, 'K-53: ceza yazilmasin',
     '            if asim_kural and t.get("hedef") is not None:\n                asim = self.m.NewIntVar(0, kisi_sayisi, "ha_%d_%d" % (gun, saat))',
     '            if False:\n                asim = self.m.NewIntVar(0, kisi_sayisi, "ha_%d_%d" % (gun, saat))',
     'testler/test_hedef_asimi.py'),
    ('hedef_asimi', M, 'K-53: asim hedefin altini da cezalandirsin (mutlak)',
     '                self._kisit(asim >= sum(atanmis) - t["hedef"])',
     '                self._kisit(asim >= t["hedef"] - sum(atanmis))',
     'testler/test_hedef_asimi.py'),
    ('hedef_asimi', M, 'K-53: KAPSAMA profilinde agirlik DENGELI ile ayni',
     '    "HEDEF_ASIMI":           {"DENGELI": 3, "KAPSAMA": 1,  "CALISAN": 4},',
     '    "HEDEF_ASIMI":           {"DENGELI": 3, "KAPSAMA": 3,  "CALISAN": 4},',
     'testler/test_hedef_asimi.py'),
    ('hedef_asimi', K, 'K-53 dogrulayici: esitlik de ihlal',
     '        if sayi > hedef:\n            cikan.append(_ihlal("HEDEF_ASIMI"',
     '        if sayi >= hedef:\n            cikan.append(_ihlal("HEDEF_ASIMI"',
     'testler/test_hedef_asimi.py'),
    # ---- sure yetmedi (1 Ekim aksami): testler artik yarisla degil
    # ---- enjeksiyonla kuruluyor -- mekanizmayi hala isirdiklarinin kaniti
    ('sure_yetmedi', C, 'butce dolunca "cozumsuz" desin (kanitsiz cumle)',
     '        "durum": "sure_yetmedi",',
     '        "durum": "cozumsuz",',
     'testler/test_sure_yetmedi.py'),
    ('sure_yetmedi', C, 'teshis istenmeden kossun',
     '    if ayar.get("teshis_iste"):',
     '    if True:',
     'testler/test_sure_yetmedi.py'),
    ('sure_yetmedi', C, 'istenerek kosan teshis "kesin" desin',
     '        return teshis_koy(girdi, kuruldu, istatistik, ayar, kesin=False)',
     '        return teshis_koy(girdi, kuruldu, istatistik, ayar, kesin=True)',
     'testler/test_sure_yetmedi.py'),
    ('sure_yetmedi', C, 'verilen sure bildirilmesin',
     '        "verilen_saniye": ayar["azami_saniye"],',
     '        "verilen_saniye": None,',
     'testler/test_sure_yetmedi.py'),
    ('sure_yetmedi', C, '"neden oldugunu arastir" secenegi sunulmasin',
     '        "teshis_istenebilir": True,',
     '        "teshis_istenebilir": False,',
     'testler/test_sure_yetmedi.py'),
    # ---- K-54 / T-29 (1 Ekim aksami): donmus gun -- olan oldu
    ('donmus', M, 'K-54: yalniz gecmise ait kisit dusmesin (gecmisin kusuru cozumsuz etsin)',
     '        if donmus_var == len(vars_):\n            c.clear_linear()',
     '        if False:\n            c.clear_linear()',
     'testler/test_donmus_gun.py'),
    ('donmus', M, 'K-54: gecmiste asilmis sinir kirpilmasin',
     '        if sabit + serbest_lo > hi:',
     '        if False:',
     'testler/test_donmus_gun.py'),
    ('donmus', M, 'K-54: donmus atama modelde sayilmasin (x=0)',
     '        self._domain_sabitle(v, 1)\n        molalar = secilen[0][1]',
     '        self._domain_sabitle(v, 0)\n        molalar = secilen[0][1]',
     'testler/test_donmus_gun.py'),
    ('donmus', C, 'K-54: cozucu donmus gunu de kendi uretsin (satirlar iki kez)',
     '        if d in kuruldu.donmus:\n            continue          # K-54: donmus gun satirlari plandan AYNEN gecer',
     '        if False:\n            continue          # K-54: donmus gun satirlari plandan AYNEN gecer',
     'testler/test_donmus_gun.py'),
    ('donmus', K, 'K-54 dogrulayici: plandan SILINEN satiri gormesin',
     '        if b == v:\n            continue\n        calisan, gun, bas, bit = k',
     '        if b <= v:\n            continue\n        calisan, gun, bas, bit = k',
     'testler/test_donmus_gun.py'),
    ('donmus', D, 'K-54 dogrulayici: serbest gundeki ihlali de gecmis saysin',
     '               and (i.get("gun") in donmus\n                    or (i.get("gun") is None\n                        and i.get("kural") in GUNSUZ_TAVAN_KURALLARI))]',
     '               and True]',
     'testler/test_donmus_gun.py'),
    ('donmus', D, 'K-54 dogrulayici: gunsuz her kural (adalet, saat dengesi) gecmis sayilabilsin',
     '                        and i.get("kural") in GUNSUZ_TAVAN_KURALLARI))]',
     '                        and True))]',
     'testler/test_donmus_gun.py'),
    ('donmus', D, 'K-54 kapi: gecmis ihlali de saysin',
     '                 and not i.get("gecmis")]          # K-54: olan oldu, kapi saymaz',
     '                 and True]          # K-54: olan oldu, kapi saymaz',
     'testler/test_donmus_gun.py'),
    ('donmus', D, 'K-54: plansiz donmus gun "denetlenemedi" demesin',
     '            if (girdi.get("donmus_gunler") or []) and girdi.get("mevcut_plan") is None:',
     '            if False:',
     'testler/test_donmus_gun.py'),
    # ---- T-38 (1 Ekim gecesi): sabit atama = sabitleme kilidi, saat+ekip ile
    ('sabit', M, 'T-38: esleme ekibe bakmasin',
     '            if ekip is not None and t.get("ekip") is not None and t.get("ekip") != ekip:\n                continue',
     '            if False:\n                continue',
     'testler/test_sabit_atama.py'),
    ('sabit', M, 'T-38: saatle esleme yapilmasin (yalniz sablon kimligi)',
     '        bas, bit = satir.get("bas"), satir.get("bit")\n        if bas is None or bit is None:\n            return None',
     '        bas, bit = satir.get("bas"), satir.get("bit")\n        if True:\n            return None',
     'testler/test_sabit_atama.py'),
    ('sabit', K, 'T-38 dogrulayici: sabit atamalar denetlenmesin',
     '    for a in girdi.get("sabit_atamalar", []) or []:\n        if ("bas" in a and "bit" in a) or a.get("sablon") is not None:',
     '    for a in []:\n        if ("bas" in a and "bit" in a) or a.get("sablon") is not None:',
     'testler/test_sabit_atama.py'),
    ('sabit', K, 'T-38 dogrulayici: ekip yazilmissa da ekibe bakmasin',
     '                    (k.get("ekip") is None or a.get("ekip") == k.get("ekip")):',
     '                    True:',
     'testler/test_sabit_atama.py'),
    # ---- K-56 (1 Ekim gecesi): devreden kapsama -- iki taraf
    ('devir', M, 'K-56: atanmis sayimina devreden eklenmesin',
     '        devir = self._devir_sayisi_dilim(ekip, dilim)          # K-56\n        if devir:\n            cikan.append(devir)\n        return cikan',
     '        devir = self._devir_sayisi_dilim(ekip, dilim)          # K-56\n        if False:\n            cikan.append(devir)\n        return cikan',
     'testler/test_devir_kapsama.py'),
    ('devir', TS, 'K-56: on kontrol devreden kapsamayi bilmesin',
     '        if kuruldu._devir_sayisi(t.get("ekip"), gun, saat) >= t["asgari"]:',
     '        if False:',
     'testler/test_devir_kapsama.py'),
    ('devir', M, 'K-56: gecmis varken de elle verilen sayi kullanilsin',
     '        if gecmis_var:\n            for c in girdi.get("calisanlar") or []:\n                for gun, bas, bit, _ in _gecmis_kayitlari(c):',
     '        if gecmis_var and False:\n            for c in girdi.get("calisanlar") or []:\n                for gun, bas, bit, _ in _gecmis_kayitlari(c):',
     'testler/test_devir_kapsama.py'),
    ('devir', M, 'K-56: tek sayimda ilk ekibe bakilmasin',
     '                    if self.cok_ekipli_sayim == "tek":\n                        if not ekipler or ekipler[0] != ekip:\n                            continue',
     '                    if self.cok_ekipli_sayim == "tek":\n                        if False:\n                            continue',
     'testler/test_devir_kapsama.py'),
    ('devir', K, 'K-56 dogrulayici: kapsama kurallari devredeni gormesin',
     '    devir = devir_atamalari(girdi)\n    return list(atamalar) + devir if devir else atamalar',
     '    devir = devir_atamalari(girdi)\n    return atamalar',
     'testler/test_devir_kapsama.py'),
    ('devir', K, 'K-56 dogrulayici: elle verilen sayi uretilmesin',
     '        for i in range(max(0, kisi)):',
     '        for i in range(0):',
     'testler/test_devir_kapsama.py'),
    # ---- kalite olcumu araclari (T-60, 2 Ekim) -- cozucu
    ('kalite', C, 'T-60: dagilim agirliksiz toplansin (amacla tutmaz)',
     '        d["ceza"] += agirlik * deger',
     '        d["ceza"] += deger',
     'testler/test_kalite_olcumu.py'),
    ('kalite', C, 'T-60: esik "esit" halini atlasin',
     '        esikler[ad] = next((sn for sn, amac, _ in egri if amac <= hedef), None) if kazanc > 0 else 0.0',
     '        esikler[ad] = next((sn for sn, amac, _ in egri if amac < hedef), None) if kazanc > 0 else 0.0',
     'testler/test_kalite_olcumu.py'),
    ('kalite', C, 'T-60: inceltme son noktayi dusursun',
     '        if secilen[-1] != egri[-1]:\n            secilen.append(egri[-1])',
     '        if False:\n            secilen.append(egri[-1])',
     'testler/test_kalite_olcumu.py'),
    ('kalite', C, 'T-60: cozucu parametresi sessizce yutulsun',
     '        setattr(cozucu.parameters, ad, deger)',
     '        pass',
     'testler/test_kalite_olcumu.py'),
    ('kalite', C, 'T-60: sure/isci parametresi buradan da gecsin',
     '        if ad in ("max_time_in_seconds", "num_search_workers", "num_workers"):',
     '        if False:',
     'testler/test_kalite_olcumu.py'),
    ('kalite', C, 'T-60: egri hic yazilmasin',
     '        self.egri.append((round(time.time() - (self.ana_basladi or self.baslangic), 2),\n                          deger, sinir))',
     '        pass',
     'testler/test_kalite_olcumu.py'),
    # ---- fazla mesai = yasal tanim (K-57, 2 Ekim) -- iki yari
    ('fmtanim', D, 'K-57 geri: dogrulayici metrigi ucret saatine baksin',
     '        kisi_net[a["calisan"]] = kisi_net.get(a["calisan"], 0.0) + zaman.net_saat(a)',
     '        kisi_net[a["calisan"]] = kisi_net.get(a["calisan"], 0.0) + zaman.ucret_saat(a)',
     'testler/test_fazla_mesai_tanimi.py'),
    ('fmtanim', D, 'K-57: dogrulayici yari zamanliya da yazsin',
     '        sozlesme = c.get("sozlesme") or {}\n        if sozlesme.get("tip") == "yari_zamanli":\n            continue\n        soz = sozlesme.get("haftalik_saat")\n        if soz is not None:\n            fazla += max(0.0, kisi_net.get(c["id"], 0.0) - soz)',
     '        sozlesme = c.get("sozlesme") or {}\n        if False:\n            continue\n        soz = sozlesme.get("haftalik_saat")\n        if soz is not None:\n            fazla += max(0.0, kisi_net.get(c["id"], 0.0) - soz)',
     'testler/test_fazla_mesai_tanimi.py'),
    ('fmtanim', C, 'K-57 geri: motor metrigi brut - mola_dk saysin',
     '        if s is not None:\n            saat = _net_saat(s)',
     '        if s is not None:\n            saat = (s["bit"] - s["bas"]) - s.get("mola_dk", 0) / 60.0',
     'testler/test_fazla_mesai_tanimi.py'),
    ('fmtanim', C, 'K-57: motor metrigi yari zamanliya da yazsin',
     '        sozlesme = c.get("sozlesme") or {}\n        if sozlesme.get("tip") == "yari_zamanli":\n            continue\n        soz = sozlesme.get("haftalik_saat")\n        if soz is not None:\n            fazla += max(0.0, net.get(c["id"], 0.0) - soz)',
     '        sozlesme = c.get("sozlesme") or {}\n        if False:\n            continue\n        soz = sozlesme.get("haftalik_saat")\n        if soz is not None:\n            fazla += max(0.0, net.get(c["id"], 0.0) - soz)',
     'testler/test_fazla_mesai_tanimi.py'),
    ('fmtanim', M, 'T-60: fazla mesai agirligi tabloyu/kiraciyi dinlemesin',
     '                self.cezalar.append((self._agirlik("FAZLA_MESAI"), fazla))',
     '                self.cezalar.append((50, fazla))',
     'testler/test_fazla_mesai_tanimi.py'),
    # ---- T-60 bulgu 8 olcum secenekleri (2 Ekim): (a) birinci asamada
    # ---- iyilestirme, (b) ipuclu + ipucusuz yan yana -- cozucu
    # ⚠ K-59 (3 Ekim): (a) artik varsayilan ACIK (sure orandan). Eski
    #   "ACIK olsun" mutasyonu tersine dondu.
    ('demir', C, 'K-59 geri: (a) varsayilan KAPALI olsun',
     '    "ilk_asama_iyilestirme_saniye": None,',
     '    "ilk_asama_iyilestirme_saniye": 0,',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'K-60: oran %80 degil %40 olsun (K-59 hali)',
     '    "ilk_asama_iyilestirme_orani": 0.8,',
     '    "ilk_asama_iyilestirme_orani": 0.4,',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'K-60: oran ayardan okunmasin (sabit %80)',
     '    tavan = float(ayar["azami_saniye"]) * float(ayar.get("ilk_asama_iyilestirme_orani", 0.8))',
     '    tavan = float(ayar["azami_saniye"]) * 0.8',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'K-60 geri: mola adimi varsayilan KAPALI olsun',
     '    "mola_adimi": True,',
     '    "mola_adimi": False,',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'K-60: mola adimi genel %2 bosluguyla dursun (0 degil)',
     '    "mola_adimi_hedef_bosluk": 0.0,',
     '    "mola_adimi_hedef_bosluk": 0.02,',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'K-60: mola adimi esigi ayardan okunmasin',
     '        geri.ayar = dict(ayar, hedef_bosluk=float(ayar.get("mola_adimi_hedef_bosluk", 0.0)))',
     '        geri.ayar = dict(ayar, hedef_bosluk=0.0)',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'K-60: mola adimi esigi hic uygulanmasin (genel %2 kalsin)',
     '        geri.ayar = dict(ayar, hedef_bosluk=float(ayar.get("mola_adimi_hedef_bosluk", 0.0)))\n',
     '',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'K-60: mola_adimi False da sabitlesin (olcum kapisi kapansin)',
     '    mola_adimi = bool(ayar.get("mola_adimi", True))',
     '    mola_adimi = True',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'ErkenDur: esitlikte "optimum" degil "hedef_bosluk" densin (eski)',
     '        if deger == sinir:',
     '        if deger == 0 and sinir == 0:',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'K-59: None orandan degil sifirdan okunsun',
     '    istenen = tavan if istenen is None else float(istenen)   # K-59: None = orandan',
     '    istenen = 0.0 if istenen is None else float(istenen)',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'K-59: sifir kapatmasin (orana dussun)',
     '    if istenen <= 0:\n        return                                   # 0 = kapali (olcum: eski davranis)',
     '    if istenen < 0:\n        return',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'mola adimi: atamalar sabitlenmesin',
     '        atamalar_sabit = _atamalari_sabitle(kuruldu) > 0',
     '        atamalar_sabit = True',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'mola adimi: molalar da sabitlensin',
     '    for v in kuruldu.x.values():\n        deger = ipucu.get(v.Index())',
     '    for v in list(kuruldu.x.values()) + list(kuruldu.mola.values()) + list(kuruldu.dinlenme.values()):\n        deger = ipucu.get(v.Index())',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'mola adimi: ipucu yokken de uygulandi densin',
     '    if mola_adimi and iki_asama:\n        atamalar_sabit = _atamalari_sabitle(kuruldu) > 0',
     '    if mola_adimi:\n        atamalar_sabit = _atamalari_sabitle(kuruldu) > 0 or True',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(b) varsayilan ACIK olsun',
     '    "paralel_ipucusuz_isci": 0,',
     '    "paralel_ipucusuz_isci": 1,',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(a) iyilestirme AMACSIZ kossun',
     '    amaci_geri_koy()\n    if bilgi["ipucusuz"]:',
     '    if bilgi["ipucusuz"]:',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(a) ipucusuz bayragi yok sayilsin',
     '    if bilgi["ipucusuz"]:\n        kuruldu.m.ClearHints()',
     '    if False:\n        kuruldu.m.ClearHints()',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(a) plan bulunamayinca amacsiz ipucu GERI yazilmasin',
     '        proto.solution_hint.vars.extend(yedek[0])\n        proto.solution_hint.values.extend(yedek[1])',
     '        pass',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(a) iyilesmis plan ipucuya yazilmasin',
     '        _tam_ipucu_yaz(kuruldu, c2)',
     '        pass',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(a) sure butceden dusulmesin',
     '    saniye = min(min(istenen, tavan) - dusulecek, kalan)',
     '    saniye = istenen',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(a) iyilestirme butcenin tamamini alabilsin',
     '    saniye = min(min(istenen, tavan) - dusulecek, kalan)',
     '    saniye = min(istenen - dusulecek, kalan)',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(b) secim tersine: amaci BUYUK olan',
     '    return min(planli, key=lambda a: (a["cozucu"].ObjectiveValue(), a["sira"]))',
     '    return max(planli, key=lambda a: (a["cozucu"].ObjectiveValue(), a["sira"]))',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(b) plansiz arama da secilebilsin',
     '    planli = [a for a in adaylar if a["durum"] in (cp_model.OPTIMAL, cp_model.FEASIBLE)]\n    if not planli:',
     '    planli = list(adaylar)\n    if not planli:',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(b) kopyanin ipucu silinmesin',
     '    kopya.ClearHints()\n',
     '',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(b) isciler bolusulmesin',
     '    cozucu.parameters.num_search_workers = ipuclu_isci',
     '    cozucu.parameters.num_search_workers = isci',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, '(b) ipucu yokken de paralel kossun',
     '        if iki_asama:\n            cozucu, geri, durum, paralel',
     '        if True:\n            cozucu, geri, durum, paralel',
     'testler/test_demir_secenekleri.py'),
    # ---- O-16 (6 Ekim): kisitli bir modelin (mola adimi: atamalar sabit; fazla
    # ---- mesaisiz kosu) siniri ve optimumu PLANIN siniri/optimumu diye yazilmaz
    ('demir', C, 'O-16 geri: kisitli kosuda kuresel alt sinir yazilsin',
     '        "alt_sinir": sinir if kapsam is None else None,',
     '        "alt_sinir": sinir,',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: ortak aramada da kuresel sinir silinsin',
     '        "alt_sinir": sinir if kapsam is None else None,',
     '        "alt_sinir": None,',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16 geri: kisitli kosuda uzaklik %0 yazilsin',
     '        if kapsam or ipucu_plani_dondu:\n            metrikler["optimuma_uzaklik_yuzde"] = None      # O-16 / K-63: kuresel kanit yok',
     '        if False:\n            metrikler["optimuma_uzaklik_yuzde"] = None',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: uzaklik ortak aramada da silinsin',
     '        if kapsam or ipucu_plani_dondu:\n            metrikler["optimuma_uzaklik_yuzde"] = None      # O-16 / K-63: kuresel kanit yok',
     '        if True:\n            metrikler["optimuma_uzaklik_yuzde"] = None',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16 geri: kisitli kosu duz "optimum" desin',
     '    if kapsam and sebep in _KANIT_SEBEPLERI:\n        sebep = kapsam + "_" + sebep',
     '    if False:\n        sebep = kapsam + "_" + sebep',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: on ek ortak aramada da yazilsin',
     '    if kapsam and sebep in _KANIT_SEBEPLERI:\n        sebep = kapsam + "_" + sebep',
     '    if sebep in _KANIT_SEBEPLERI:\n        sebep = "mola_adimi_" + sebep',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: "hedef_bosluk" on eksiz kalsin',
     '_KANIT_SEBEPLERI = ("optimum", "hedef_bosluk")',
     '_KANIT_SEBEPLERI = ("optimum",)',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: kanit iddia etmeyen sebep de on ek alsin',
     '    if kapsam and sebep in _KANIT_SEBEPLERI:\n        sebep = kapsam + "_" + sebep',
     '    if kapsam:\n        sebep = kapsam + "_" + sebep',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: mola adiminin kendi siniri yazilmasin',
     '        "mola_adimi_alt_sinir": sinir if kapsam == "mola_adimi" else None,',
     '        "mola_adimi_alt_sinir": None,',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: mola adimi siniri ortak aramada da yazilsin',
     '        "mola_adimi_alt_sinir": sinir if kapsam == "mola_adimi" else None,',
     '        "mola_adimi_alt_sinir": sinir,',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: mola adimi tam model sayilsin',
     '    if atamalar_sabit:\n        return "mola_adimi"',
     '    if False:\n        return "mola_adimi"',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: (b) kollari kisitli kosuda isaretlenmesin',
     '    if paralel and kapsam:\n        _paralel_kisitli_isaretle(paralel, kapsam)',
     '    if False:\n        _paralel_kisitli_isaretle(paralel, kapsam)',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: (b) kollarinin siniri silinmesin',
     '        b["alt_sinir"] = None\n        if b.get("durma_sebebi") in _KANIT_SEBEPLERI:',
     '        if b.get("durma_sebebi") in _KANIT_SEBEPLERI:',
     'testler/test_demir_secenekleri.py'),
    ('demir', C, 'O-16: (b) kollarinin sebebi on eksiz kalsin',
     '            b["durma_sebebi"] = kapsam + "_" + b["durma_sebebi"]',
     '            pass',
     'testler/test_demir_secenekleri.py'),
    # ---- "once fazla mesaisiz" (T-60 bulgu 20-21) -- K-61 (6 Ekim): URUNUN
    # ---- VARSAYILANI; HAKEM AGIRLIKLARDIR: bulunan plan yalniz baslangic
    # ---- noktasidir, alanlar geri acilir (7 Ekim, O-18). Sert kesim yalniz
    # ---- olcum secenegidir (`fazla_mesai_sifirda_tut`).
    ('fm_sifir', C, 'K-61: varsayilan KAPALI olsun (karar geri alinsin)',
     '    "fazla_mesai_once_sifir": True,',
     '    "fazla_mesai_once_sifir": False,',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: sert kesim urunun varsayilani olsun (6 Ekim gecesinin hali)',
     '    "fazla_mesai_sifirda_tut": False,',
     '    "fazla_mesai_sifirda_tut": True,',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'secenek yok sayilsin',
     '    fm_eski = (_fazla_mesaiyi_sifirla(kuruldu)\n               if ayar.get("fazla_mesai_once_sifir") else [])',
     '    fm_eski = []',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'secenek kapaliyken de uygulansin',
     '    fm_eski = (_fazla_mesaiyi_sifirla(kuruldu)\n               if ayar.get("fazla_mesai_once_sifir") else [])',
     '    fm_eski = _fazla_mesaiyi_sifirla(kuruldu)',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: bulununca hep 0\'da tutulsun (sert kesim; ilke cignenir)',
     '            sifirda = bulundu and bool(ayar.get("fazla_mesai_sifirda_tut"))',
     '            sifirda = bulundu',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: olcum secenegi acikken de 0\'da tutulmasin',
     '            sifirda = bulundu and bool(ayar.get("fazla_mesai_sifirda_tut"))',
     '            sifirda = False',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: bulunamayinca da "0\'da tutuldu" densin',
     '            sifirda = bulundu and bool(ayar.get("fazla_mesai_sifirda_tut"))',
     '            sifirda = bool(ayar.get("fazla_mesai_sifirda_tut"))',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: ciktida "sifirda_tutuldu" hep False yazsin',
     '                "sifirda_tutuldu": sifirda}',
     '                "sifirda_tutuldu": False}',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: ciktida "sifirda_tutuldu" bulundu\'yu yazsin',
     '                "sifirda_tutuldu": sifirda}',
     '                "sifirda_tutuldu": bulundu}',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: alanlar yalniz bulunamayinca geri acilsin (6 Ekim gecesi)',
     '            if not sifirda:\n                # ⚠ HAKEM AGIRLIKLARDIR (K-61).',
     '            if not bulundu:\n                # ⚠ HAKEM AGIRLIKLARDIR (K-61).',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: alanlar hic geri acilmasin',
     '            if not sifirda:\n                # ⚠ HAKEM AGIRLIKLARDIR (K-61).',
     '            if False:\n                # ⚠ HAKEM AGIRLIKLARDIR (K-61).',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: sert kesimde de alanlar geri acilsin',
     '            if not sifirda:\n                # ⚠ HAKEM AGIRLIKLARDIR (K-61).',
     '            if True:\n                # ⚠ HAKEM AGIRLIKLARDIR (K-61).',
     'testler/test_fazla_mesai_once_sifir.py'),
    # ⚠ 7 Ekim 04:00: bu mutasyon once `_fazla_mesaiyi_serbest_birak`in hemen
    #   ardina ClearHints koyuyordu -- ipucu o noktada HENUZ YAZILMAMISTI
    #   (`_tam_ipucu_yaz` sonra), yani mutasyon davranisi degistirmiyordu ve
    #   "yasadi" (esdeger mutant). Simdi ipucu YAZILDIKTAN sonra siliniyor;
    #   yakalayan test ipucuyu iyilestirme girisinde dogrudan okur.
    ('fm_sifir', C, 'O-18: ipucu yazildiktan sonra silinsin (fazla mesaisiz plan kaybolsun)',
     '        _tam_ipucu_yaz(kuruldu, c)\n        _ilk_asamada_iyilestir(kuruldu, ayar, c, amaci_geri_koy, basladi, dusulecek)',
     '        _tam_ipucu_yaz(kuruldu, c)\n        if fm_eski:\n            kuruldu.m.ClearHints()\n        _ilk_asamada_iyilestir(kuruldu, ayar, c, amaci_geri_koy, basladi, dusulecek)',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: ipucu fm degerleri silinsin (yarim ipucu; fazla mesaisiz baslangic kaybolsun)',
     '        _tam_ipucu_yaz(kuruldu, c)\n        _ilk_asamada_iyilestir(kuruldu, ayar, c, amaci_geri_koy, basladi, dusulecek)',
     '        _tam_ipucu_yaz(kuruldu, c)\n        if fm_eski:\n            _p = kuruldu.m.Proto(); _fmi = {i for i, _ in fm_eski}\n            _cift = [(a, b) for a, b in zip(_p.solution_hint.vars, _p.solution_hint.values) if a not in _fmi]\n            _p.solution_hint.vars.clear(); _p.solution_hint.values.clear(); _p.solution_hint.vars.extend([a for a, _ in _cift]); _p.solution_hint.values.extend([b for _, b in _cift])\n        _ilk_asamada_iyilestir(kuruldu, ayar, c, amaci_geri_koy, basladi, dusulecek)',
     'testler/test_fazla_mesai_once_sifir.py'),
    # ⚠ 7 Ekim 04:45 (bagimsiz inceleme A): mola adimina giden ipucu da
    #   denetlenmeli -- iki mutant yasiyordu. Yakalayan test ipucuyu ana
    #   aramanin girisinde (`_durgunluk_bekcisiyle_coz`) okur.
    ('fm_sifir', C, 'O-18: ipucunun fm degerleri hep 0 yazilsin (mola adimina yanlis ipucu)',
     '    proto.solution_hint.vars.extend(list(range(len(degerler))))\n    proto.solution_hint.values.extend(degerler)',
     '    _fmi = {v.Index() for _, v in kuruldu.cezalar if v.Name().startswith("fm_")}\n    degerler = [0 if i in _fmi else d for i, d in enumerate(degerler)]\n    proto.solution_hint.vars.extend(list(range(len(degerler))))\n    proto.solution_hint.values.extend(degerler)',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: iyilestirmeden sonra ipucunun fm degerleri silinsin (mola adimina yarim ipucu)',
     '        else:\n            _tam_ipucu_yaz(kuruldu, c2)\n    else:',
     '        else:\n            _tam_ipucu_yaz(kuruldu, c2)\n            _fmi = {v.Index() for _, v in kuruldu.cezalar if v.Name().startswith("fm_")}\n            _cift = [(a, b) for a, b in zip(proto.solution_hint.vars, proto.solution_hint.values) if a not in _fmi]\n            proto.solution_hint.vars.clear(); proto.solution_hint.values.clear(); proto.solution_hint.vars.extend([a for a, _ in _cift]); proto.solution_hint.values.extend([b for _, b in _cift])\n    else:',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: iyilestirme ipucudan KOTU plan dondurse de ipucu ezilsin (koruma yok)',
     '        if bilgi["iyilesmis_amac"] > amacsiz_amac:',
     '        if False:',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-18: koruma ters calissin (iyi plani at, kotuyu yaz)',
     '        if bilgi["iyilesmis_amac"] > amacsiz_amac:',
     '        if bilgi["iyilesmis_amac"] <= amacsiz_amac:',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulunamayinca not dusulmesin (sessiz geri donus)',
     '            if not bulundu:\n                kuruldu.notlar.append(',
     '            if False:\n                kuruldu.notlar.append(',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulununca da not dusulsun',
     '            if not bulundu:\n                kuruldu.notlar.append(',
     '            if True:\n                kuruldu.notlar.append(',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'not "en aza indirilir" diye kanit iddia etsin',
     '                    "(agirlikli arama azaltmaya calisir; en azi oldugu kanitli degildir)"',
     '                    "(yumusak cezayla en aza indirilir)"',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulunamayinca yeniden aranmasin',
     '                durum, c = _gecerli_plan_yeniden_ara(kuruldu, ayar, basladi)',
     '                pass',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'plan yokken de "bulundu" densin',
     '            bulundu = durum in (cp_model.OPTIMAL, cp_model.FEASIBLE)',
     '            bulundu = True',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'sure yetmemesi de kanit sayilsin',
     '                "kanitlandi_yok": durum == cp_model.INFEASIBLE,',
     '                "kanitlandi_yok": not bulundu,',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'not hep "kanitlandi" desin',
     '                       if durum == cp_model.INFEASIBLE\n                       else "bu surede bulunamadi" + (',
     '                       if True\n                       else "bu surede bulunamadi" + (',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'not hep "molalar sabitken" desin',
     '("molalar sabitken " if mola_sabit else "")',
     '("molalar sabitken ")',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'sonuc ciktiya yazilmasin',
     '        "fazla_mesai_once_sifir": getattr(kuruldu, "fazla_mesai_once_sifir", None),',
     '        "fazla_mesai_once_sifir": None,',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'sifirlama butun ceza degiskenlerine dokunsun',
     '        if not v.Name().startswith("fm_"):\n            continue\n',
     '',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'sifirlama alani daraltmasin',
     '        dom.extend([0, 0])\n    return eski',
     '        dom.extend(eski[-1][1])\n    return eski',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'zaten 0 olan alan da sabitlenmis sayilsin (CALISAN)',
     '        if list(dom) == [0, 0]:\n            continue\n',
     '',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'geri alma eski alani degil [0,1] yazsin',
     '    for ix, alan in eski:\n        dom = proto.variables[ix].domain\n        dom.clear()\n        dom.extend(alan)',
     '    for ix, alan in eski:\n        dom = proto.variables[ix].domain\n        dom.clear()\n        dom.extend([0, 1])',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'yeniden arama butcenin tamamini alsin',
     '    c.parameters.max_time_in_seconds = max(1.0, min(_ilk_asama_payi(ayar), kalan))',
     '    c.parameters.max_time_in_seconds = float(ayar["azami_saniye"])',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'yeniden arama kalan butceye bakmasin',
     '    c.parameters.max_time_in_seconds = max(1.0, min(_ilk_asama_payi(ayar), kalan))',
     '    c.parameters.max_time_in_seconds = _ilk_asama_payi(ayar)',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'yeniden arama paya bakmasin (kalanin tamami)',
     '    c.parameters.max_time_in_seconds = max(1.0, min(_ilk_asama_payi(ayar), kalan))',
     '    c.parameters.max_time_in_seconds = max(1.0, kalan)',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'yeniden arama tabani kalksin (sifir/eksi sure)',
     '    c.parameters.max_time_in_seconds = max(1.0, min(_ilk_asama_payi(ayar), kalan))',
     '    c.parameters.max_time_in_seconds = min(_ilk_asama_payi(ayar), kalan)',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'yeniden arama 1 sn pay birakmasin',
     '    kalan = float(ayar["azami_saniye"]) - (time.time() - basladi) - 1.0\n    c = cp_model.CpSolver()',
     '    kalan = float(ayar["azami_saniye"]) - (time.time() - basladi)\n    c = cp_model.CpSolver()',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'basarisiz denemenin suresi iyilestirmeden dusulmesin',
     '    saniye = min(min(istenen, tavan) - dusulecek, kalan)',
     '    saniye = min(istenen, tavan, kalan)',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'deneme suresi yalniz paydan dussun (acik istekten degil)',
     '    saniye = min(min(istenen, tavan) - dusulecek, kalan)',
     '    saniye = min(istenen, tavan - dusulecek, kalan)',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'basarili denemenin suresi de iyilestirmeden dusulsun',
     '        dusulecek = 0.0\n        if fm_eski:\n            bulundu = durum in (cp_model.OPTIMAL, cp_model.FEASIBLE)\n            deneme_sn = time.time() - basladi     # butun denemelerin toplami\n',
     '        dusulecek = 0.0\n        if fm_eski:\n            bulundu = durum in (cp_model.OPTIMAL, cp_model.FEASIBLE)\n            deneme_sn = time.time() - basladi\n            dusulecek = deneme_sn\n',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'kanitin kapsami ciktida hep "sabit" yazsin',
     '                "molalar_sabit": mola_sabit,\n',
     '                "molalar_sabit": True,\n',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-16: sert kesim tam model sayilsin',
     '    if (getattr(kuruldu, "fazla_mesai_once_sifir", None) or {}).get("sifirda_tutuldu"):\n        return "fazla_mesaisiz"',
     '    if False:\n        return "fazla_mesaisiz"',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-16/O-18: urun yolu (bulundu, alanlar acik) kisitli sayilsin',
     '    if (getattr(kuruldu, "fazla_mesai_once_sifir", None) or {}).get("sifirda_tutuldu"):',
     '    if (getattr(kuruldu, "fazla_mesai_once_sifir", None) or {}).get("bulundu"):',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-16: deneme yapildiysa hep kisitli sayilsin',
     '    if (getattr(kuruldu, "fazla_mesai_once_sifir", None) or {}).get("sifirda_tutuldu"):',
     '    if getattr(kuruldu, "fazla_mesai_once_sifir", None):',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'iyilestirme egrisi yazilmasin',
     '    bilgi["iyilesme"] = _iyilesme_ozeti(sayac.egri, nokta=24)',
     '    bilgi["iyilesme"] = None',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'iyilestirme egrisine nokta eklenmesin',
     '        self.egri.append((round(time.time() - self.basladi, 2),\n                          self.ObjectiveValue(), self.BestObjectiveBound()))',
     '        pass',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'amac degeri yuvarlanmasin, kirpilsin',
     '        return int(round(cozucu.ObjectiveValue()))\n    except Exception:',
     '        return int(cozucu.ObjectiveValue())\n    except Exception:',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-16: fazla mesaisiz siniri yazilmasin',
     '        "fazla_mesaisiz_alt_sinir": sinir if kapsam == "fazla_mesaisiz" else None,',
     '        "fazla_mesaisiz_alt_sinir": None,',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'O-16: fazla mesaisiz siniri her kosuda yazilsin',
     '        "fazla_mesaisiz_alt_sinir": sinir if kapsam == "fazla_mesaisiz" else None,',
     '        "fazla_mesaisiz_alt_sinir": sinir,',
     'testler/test_fazla_mesai_once_sifir.py'),
    # ---- YENIDEN BASLATMA -- T-60 bulgu 25 (7 Ekim): `fazla_mesaisiz_deneme`
    # ---- (varsayilan 1). Pay N'e bolunur, her deneme farkli tohum, ilk bulunan
    # ---- alinir, INFEASIBLE kanittir. Yakalayan testler: bolum 7.
    ('fm_sifir', C, 'bulgu 25: deneme sayisi yok sayilsin (hep tek deneme)',
     '    adet = _deneme_siniri(ayar)\n',
     '    adet = 1\n',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: tohum degismesin (her deneme ayni arama)',
     '        c.parameters.random_seed = i + 1          # 1 = CP-SAT varsayilani (bugunku arama)',
     '        c.parameters.random_seed = 1',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: ilk tohum 0 olsun (bugunku arama degisir; kutuphane varsayilani 1)',
     '        c.parameters.random_seed = i + 1          # 1 = CP-SAT varsayilani (bugunku arama)',
     '        c.parameters.random_seed = i',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: pay bolunmesin (her deneme payin tamami; butce asilir)',
     '    parca = float(pay) if adet == 1 else max(1.0, float(pay) / adet)',
     '    parca = float(pay)',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: parca tabani kalksin (kesirli/sifir sure)',
     '    parca = float(pay) if adet == 1 else max(1.0, float(pay) / adet)',
     '    parca = float(pay) / adet',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: yeniden baslatma yapilmasin (ilk denemeden sonra dur)',
     '        if durum in (cp_model.OPTIMAL, cp_model.FEASIBLE, cp_model.INFEASIBLE):\n            break                                 # plan var, ya da yoklugu kanitli',
     '        break',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: INFEASIBLE kanit sayilmasin (kalan denemeler bosa kossun)',
     '        if durum in (cp_model.OPTIMAL, cp_model.FEASIBLE, cp_model.INFEASIBLE):\n            break                                 # plan var, ya da yoklugu kanitli',
     '        if durum in (cp_model.OPTIMAL, cp_model.FEASIBLE):\n            break',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: denemeler ciktiya yazilmasin',
     '                "denemeler": denemeler,',
     '                "denemeler": None,',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: deneme siniri ciktida hep 1 yazsin',
     '                "deneme_siniri": _deneme_siniri(ayar),',
     '                "deneme_siniri": 1,',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: not kac denemede oldugunu soylemesin',
     '                           " (%d denemede)" % len(denemeler) if len(denemeler) > 1 else "")))',
     '                           "")))',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: tek denemede de "(1 denemede)" yazsin (not siniri)',
     '                           " (%d denemede)" % len(denemeler) if len(denemeler) > 1 else "")))',
     '                           " (%d denemede)" % len(denemeler) if len(denemeler) >= 1 else "")))',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: tek denemede de 1 sn tabani uygulansin (birebir bozulur)',
     '    parca = float(pay) if adet == 1 else max(1.0, float(pay) / adet)',
     '    parca = max(1.0, float(pay) / adet)',
     'testler/test_fazla_mesai_once_sifir.py'),
    ('fm_sifir', C, 'bulgu 25: deneme sayisinin tabani kalksin (0/eksi deger)',
     '        return max(1, int(ayar.get("fazla_mesaisiz_deneme") or 1))',
     '        return int(ayar.get("fazla_mesaisiz_deneme") or 1)',
     'testler/test_fazla_mesai_once_sifir.py'),
    # ---- K-63 (7 Ekim): mola adimi yetismezse ikinci asamanin plani doner.
    ('k63', C, 'K-63 kapali: ana asama plansizsa eskisi gibi "sure yetmedi"',
     '    if durum not in (cp_model.OPTIMAL, cp_model.FEASIBLE, cp_model.INFEASIBLE) and iki_asama:\n        ipucu_plani = _ipucu_planini_al(kuruldu, ayar)',
     '    if False:\n        ipucu_plani = _ipucu_planini_al(kuruldu, ayar)',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'K-37 cignensin: INFEASIBLE (kanit) de ipucu planina cevrilsin',
     '    if durum not in (cp_model.OPTIMAL, cp_model.FEASIBLE, cp_model.INFEASIBLE) and iki_asama:\n        ipucu_plani = _ipucu_planini_al(kuruldu, ayar)',
     '    if durum not in (cp_model.OPTIMAL, cp_model.FEASIBLE) and iki_asama:\n        ipucu_plani = _ipucu_planini_al(kuruldu, ayar)',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'iki asama yokken de denensin (yarim/yok ipucu)',
     '    if durum not in (cp_model.OPTIMAL, cp_model.FEASIBLE, cp_model.INFEASIBLE) and iki_asama:\n        ipucu_plani = _ipucu_planini_al(kuruldu, ayar)',
     '    if durum not in (cp_model.OPTIMAL, cp_model.FEASIBLE, cp_model.INFEASIBLE):\n        ipucu_plani = _ipucu_planini_al(kuruldu, ayar)',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'cozucu degistirilmesin (plansiz cozucuden plan okunsun)',
     '            cozucu, durum = ipucu_plani["cozucu"], ipucu_plani["durum_kodu"]',
     '            durum = ipucu_plani["durum_kodu"]',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'not dusulmesin (sessiz geri donus)',
     '            kuruldu.notlar.append(\n                "%s surede plan uretemedi; %s dondu "',
     '            (lambda *a: None)(\n                "%s surede plan uretemedi; %s dondu "',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'durma sebebi sabitlenmis modelin "optimum"u kalsin (yanlis kanit)',
     '        sebep = "mola_adimi_yetismedi" if atamalar_sabit else "ana_asama_yetismedi"\n        sinir = None',
     '        sinir = None',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'ortak aramada da "mola_adimi_yetismedi" densin',
     '        sebep = "mola_adimi_yetismedi" if atamalar_sabit else "ana_asama_yetismedi"',
     '        sebep = "mola_adimi_yetismedi"',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'sabitlenmis modelin siniri yazilsin (O-16 cignenir)',
     '        sebep = "mola_adimi_yetismedi" if atamalar_sabit else "ana_asama_yetismedi"\n        sinir = None',
     '        sebep = "mola_adimi_yetismedi" if atamalar_sabit else "ana_asama_yetismedi"',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'ortak aramada yakinlik yuzdesi yazilsin (sabit modelin %0\'i)',
     '        if kapsam or ipucu_plani_dondu:\n            metrikler["optimuma_uzaklik_yuzde"] = None',
     '        if kapsam:\n            metrikler["optimuma_uzaklik_yuzde"] = None',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'cevirme adimi ARASIN (karar degiskenleri sabitlenmesin; gecersiz ipucuda plan uydurulur)',
     '    for sozluk in (kuruldu.x, kuruldu.mola, kuruldu.dinlenme):\n        for v in sozluk.values():\n            deger = ipucu.get(v.Index())',
     '    for sozluk in ():\n        for v in sozluk.values():\n            deger = ipucu.get(v.Index())',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'yalniz atamalar sabitlensin, molalar yeniden aransin (plan ikinci asamanin plani olmaz)',
     '    for sozluk in (kuruldu.x, kuruldu.mola, kuruldu.dinlenme):\n        for v in sozluk.values():\n            deger = ipucu.get(v.Index())',
     '    for sozluk in (kuruldu.x,):\n        for v in sozluk.values():\n            deger = ipucu.get(v.Index())',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'ceza degiskenleri de ipucuya sabitlensin (gevsek amac; butun degiskenler)',
     '    c.parameters.num_search_workers = 1\n    t0 = time.time()\n    durum = c.Solve(kuruldu.m)\n    bilgi.update',
     '    c.parameters.num_search_workers = 1\n    c.parameters.fix_variables_to_their_hinted_value = True\n    t0 = time.time()\n    durum = c.Solve(kuruldu.m)\n    bilgi.update',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'cevirme adimi butun iscilerle kossun',
     '    c.parameters.num_search_workers = 1\n    t0 = time.time()\n    durum = c.Solve(kuruldu.m)\n    bilgi.update',
     '    c.parameters.num_search_workers = isci_sayisi(ayar)\n    t0 = time.time()\n    durum = c.Solve(kuruldu.m)\n    bilgi.update',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'not plan kaynagini hep "ikinci asama" desin',
     '    if iy.get("plan_bulundu") and not iy.get("ipucu_korundu"):\n        return "ikinci_asama"',
     '    if True:\n        return "ikinci_asama"',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'ipucu korundu yolunda da "ikinci asama" desin',
     '    if iy.get("plan_bulundu") and not iy.get("ipucu_korundu"):\n        return "ikinci_asama"',
     '    if iy.get("plan_bulundu"):\n        return "ikinci_asama"',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'cevirme adiminin suresi cozum suresine eklensin (butce disi iddiasi bozulsun)',
     '            cozucu, durum = ipucu_plani["cozucu"], ipucu_plani["durum_kodu"]',
     '            cozucu, durum = ipucu_plani["cozucu"], ipucu_plani["durum_kodu"]\n            sure += ipucu_plani["saniye"]',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'kaynak ciktiya yazilmasin',
     '        "ipucu_plani": ({a: ipucu_plani.get(a) for a in ("bulundu", "saniye", "durum", "kaynak")}',
     '        "ipucu_plani": ({a: ipucu_plani.get(a) for a in ("bulundu", "saniye", "durum")}',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'cevirme adimina butcenin tamami verilsin',
     '    c.parameters.max_time_in_seconds = max(1.0, float(ayar.get("ipucu_plani_saniye", 30)))',
     '    c.parameters.max_time_in_seconds = float(ayar["azami_saniye"])',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'cevirme adiminin tabani kalksin (0 sn = hic arama)',
     '    c.parameters.max_time_in_seconds = max(1.0, float(ayar.get("ipucu_plani_saniye", 30)))',
     '    c.parameters.max_time_in_seconds = float(ayar.get("ipucu_plani_saniye", 30))',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'yarim ipucu da cevrilsin (eksik degiskenler aranir)',
     '    if len(proto.solution_hint.vars) < len(proto.variables):\n        bilgi["durum"] = "ipucu_eksik"\n        return bilgi',
     '    if False:\n        bilgi["durum"] = "ipucu_eksik"\n        return bilgi',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'ipucu plani ciktiya yazilmasin',
     '        "ipucu_plani": ({a: ipucu_plani.get(a) for a in ("bulundu", "saniye", "durum", "kaynak")}\n                        if ipucu_plani else None),',
     '        "ipucu_plani": None,',
     'testler/test_mola_adimi_yetismedi.py'),
    ('k63', C, 'ipucu plani basarisizken "bulundu" densin',
     '                  "bulundu": durum in (cp_model.OPTIMAL, cp_model.FEASIBLE),\n                  "cozucu": c})',
     '                  "bulundu": True,\n                  "cozucu": c})',
     'testler/test_mola_adimi_yetismedi.py'),
]


def main():
    suzgec = sys.argv[1] if len(sys.argv) > 1 else None
    secilen = [m for m in MUTASYONLAR if suzgec is None or suzgec in m[0]]
    testler = sorted({m[5] for m in secilen})

    print("OZGUN KOD (baslangic):")
    for t in testler:
        rc, son = _kostur(t)
        print("  %-42s %s" % (t, son))
        if rc:
            print("\n⚠ OZGUN KOD KIRMIZI -- mutasyon sonuclari anlamsiz olur. DURDU.")
            sys.exit(2)

    yasayan = atlanan = 0
    print("\nMUTASYONLAR:")
    for grup, dosya, ad, eski, yeni, test in secilen:
        yol = os.path.join(BURASI, dosya)
        orijinal = io.open(yol, encoding="utf-8").read()
        once = _md5(yol)
        if orijinal.count(eski) != 1:
            print("  [%-10s] %-46s ATLANDI (capa %d kez)"
                  % (grup, ad, orijinal.count(eski)))
            atlanan += 1
            continue
        try:
            io.open(yol, "w", encoding="utf-8", newline="").write(
                orijinal.replace(eski, yeni))
            rc, son = _kostur(test)
        finally:
            io.open(yol, "w", encoding="utf-8", newline="").write(orijinal)
        assert _md5(yol) == once, "%s geri yazilamadi!" % dosya
        durum = "OLDU" if rc else "*** YASADI ***"
        if not rc:
            yasayan += 1
        print("  [%-10s] %-46s %-14s %s" % (grup, ad, durum, son))

    print("\nOZGUN KOD (bitis):")
    for t in testler:
        rc, son = _kostur(t)
        print("  %-42s %s" % (t, son))
        if rc:
            print("\n⚠ OZGUN KOD SONDA KIRMIZI -- bir dosya geri yazilamamis olabilir.")
            sys.exit(2)
    _onbellegi_sil()

    print("\nOZET: %d mutasyon · yasayan %d · atlanan %d"
          % (len(secilen), yasayan, atlanan))
    # ⚠ 3 Ekim (O-15): "N mutasyon, hepsi oldu" iddiasi yalniz TAM kosudan
    #   yazilir; grup kosusu yalniz grubun sayisini soyler. Tam kosu damgasini
    #   dosyaya yazar ki "en son ne zaman tam kosuldu" sohbete degil depoya
    #   baglansin. Grup kosusunda damga yazilmaz.
    if suzgec is None:
        import datetime
        io.open(os.path.join(BURASI, "mutasyon-tam-kosu.txt"), "w", encoding="utf-8",
                newline="").write(
            "tam kosu: %s\nOZET: %d mutasyon | yasayan %d | atlanan %d\n"
            % (datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
               len(secilen), yasayan, atlanan))
    else:
        print("(grup kosusu: toplam iddiasi icin `py mutasyon_kostur.py` tam kosulur)")
    sys.exit(1 if (yasayan or atlanan) else 0)


if __name__ == "__main__":
    main()
